import {NextRequest,NextResponse} from "next/server";
import {createClient} from "@supabase/supabase-js";
import {createSupabaseAdmin} from "@/lib/supabase/admin";

async function member(req:NextRequest){const admin=createSupabaseAdmin(),token=req.headers.get("authorization")?.replace(/^Bearer\s+/i,""),url=process.env.NEXT_PUBLIC_SUPABASE_URL,key=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY;if(!admin||!token||!url||!key)return null;const auth=createClient(url,key,{auth:{persistSession:false}}),{data:{user}}=await auth.auth.getUser(token);if(!user)return null;const{data:contact}=await admin.from("audience_contacts").select("plan,subscription_status").eq("user_id",user.id).maybeSingle();return{admin,user,plan:contact?.plan??"free",subscriptionStatus:contact?.subscription_status??"active"}}

export async function GET(req:NextRequest){const ctx=await member(req);if(!ctx)return NextResponse.json({error:"Sign in to open the academy."},{status:401});const{admin,user,plan,subscriptionStatus}=ctx;const[courses,sections,lessons,resources,access,progress]=await Promise.all([
  admin.from("learning_courses").select("*").eq("status","published").order("sort_order"),
  admin.from("learning_sections").select("*").order("sort_order"),
  admin.from("learning_lessons").select("*").eq("status","published").order("sort_order"),
  admin.from("learning_resources").select("*").order("sort_order"),
  admin.from("course_plan_access").select("*"),
  admin.from("learning_progress").select("lesson_id,completed,progress_seconds,updated_at").eq("user_id",user.id),
]);
const error=[courses,sections,lessons,resources,access,progress].find(result=>result.error)?.error;if(error)return NextResponse.json({error:error.message},{status:503});const allowed=(courses.data??[]).filter(course=>{const plans=(access.data??[]).filter(item=>item.course_id===course.id).map(item=>item.plan_code);return plans.length===0||plans.includes(plan)}),allowedIds=new Set(allowed.map(course=>course.id)),allowedSections=(sections.data??[]).filter(section=>allowedIds.has(section.course_id)),sectionIds=new Set(allowedSections.map(section=>section.id)),allowedLessons=(lessons.data??[]).filter(item=>sectionIds.has(item.section_id)),lessonIds=new Set(allowedLessons.map(item=>item.id)),resourceRows=await Promise.all((resources.data??[]).filter(item=>lessonIds.has(item.lesson_id)).map(async item=>{if(item.resource_type!=="file")return{...item,url:item.external_url};const{data}=await admin.storage.from("course-resources").createSignedUrl(item.storage_path,3600);return{...item,url:data?.signedUrl??null}}));return NextResponse.json({courses:allowed.map(course=>({...course,sections:allowedSections.filter(section=>section.course_id===course.id).map(section=>({...section,lessons:allowedLessons.filter(item=>item.section_id===section.id).map(item=>({...item,resources:resourceRows.filter(resource=>resource.lesson_id===item.id)}))}))})),progress:progress.data??[],plan,subscriptionStatus})}

export async function POST(req:NextRequest){const ctx=await member(req);if(!ctx)return NextResponse.json({error:"Sign in to save progress."},{status:401});const{admin,user}=ctx,body=await req.json(),lessonId=String(body.lesson_id??"");const{data:lesson}=await admin.from("learning_lessons").select("id,status").eq("id",lessonId).maybeSingle();if(!lesson||lesson.status!=="published")return NextResponse.json({error:"Lesson is unavailable."},{status:404});const completed=Boolean(body.completed),{error}=await admin.from("learning_progress").upsert({user_id:user.id,lesson_id:lessonId,completed,progress_seconds:Math.max(0,Number(body.progress_seconds||0)),completed_at:completed?new Date().toISOString():null,updated_at:new Date().toISOString()});if(error)return NextResponse.json({error:error.message},{status:400});return NextResponse.json({ok:true})}
