"use client";
/* eslint-disable @typescript-eslint/no-explicit-any */
import Link from "next/link";
import {FormEvent,useCallback,useEffect,useMemo,useState} from "react";
import {Activity,Archive,BarChart3,Bell,CheckCircle2,CreditCard,Download,Flag,Image,LayoutDashboard,LifeBuoy,LoaderCircle,LogOut,Mail,Menu,MessageSquare,Plus,Search,Settings,Shield,SlidersHorizontal,Trash2,UserPlus,Users,X} from "lucide-react";
import {createSupabaseClient} from "@/lib/supabase/client";

type Row=Record<string,any>;
type Data={members:Row[];plans:Row[];subscriptions:Row[];messages:Row[];media:Row[];features:Row[];planFeatures:Row[];audit:Row[]};
const empty:Data={members:[],plans:[],subscriptions:[],messages:[],media:[],features:[],planFeatures:[],audit:[]};
const sections=[
  ["overview","Overview",LayoutDashboard],["members","Members",Users],["subscriptions","Subscriptions",CreditCard],["plans","Plans & access",SlidersHorizontal],["community","Community",MessageSquare],["media","Media",Image],["marketing","Marketing",Mail],["audit","Audit log",Activity],["settings","Settings",Settings]
] as const;
const date=(v?:string)=>v?new Date(v).toLocaleDateString(undefined,{year:"numeric",month:"short",day:"numeric"}):"—";
const money=(v:number,c:string)=>new Intl.NumberFormat(undefined,{style:"currency",currency:c||"USD"}).format(v||0);

export default function Admin(){
  const db=useMemo(()=>createSupabaseClient(),[]),[section,setSection]=useState("overview"),[data,setData]=useState<Data>(empty),[token,setToken]=useState(""),[loading,setLoading]=useState(true),[busy,setBusy]=useState(""),[error,setError]=useState(""),[notice,setNotice]=useState(""),[search,setSearch]=useState(""),[mobile,setMobile]=useState(false),[now]=useState(()=>Date.now());
  const load=useCallback(async(t?:string)=>{const access=t||token;if(!access)return;setLoading(true);const r=await fetch("/api/admin",{headers:{Authorization:`Bearer ${access}`}}),j=await r.json();if(!r.ok)setError(j.error||"Could not load control center.");else{setData(j);setError("")}setLoading(false)},[token]);
  useEffect(()=>{db?.auth.getSession().then(({data:{session}})=>{if(!session?.access_token){setError("Sign in with an administrator account.");setLoading(false);return}setToken(session.access_token);load(session.access_token)})},[db,load]);
  async function act(action:string,payload:Row={},confirmText?:string){if(confirmText&&!confirm(confirmText))return;setBusy(action+String(payload.id||payload.user_id||payload.code||""));setNotice("");const r=await fetch("/api/admin",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${token}`},body:JSON.stringify({action,...payload})}),j=await r.json();if(!r.ok)setError(j.error||"Action failed.");else{setError("");setNotice("Saved successfully.");await load()}setBusy("")}
  const memberById=Object.fromEntries(data.members.map(m=>[m.user_id,m]));
  const filtered=data.members.filter(m=>`${m.email} ${m.profiles?.display_name??""}`.toLowerCase().includes(search.toLowerCase()));
  const activeSubs=data.subscriptions.filter(s=>["active","trialing"].includes(s.status));
  const expiring=activeSubs.filter(s=>s.ends_at&&new Date(s.ends_at).getTime()-now<30*864e5).length;
  const opted=data.members.filter(m=>m.marketing_consent).length;
  const title=sections.find(x=>x[0]===section)?.[1]??"Overview";
  function csv(){const rows=[["Name","Email","Role","Plan","Status","Marketing","Lifecycle","Joined"],...filtered.map(m=>[m.profiles?.display_name,m.email,m.profiles?.role,m.plan,m.subscription_status,m.marketing_consent?"Yes":"No",m.lifecycle_stage,m.created_at])],content=rows.map(r=>r.map(x=>`"${String(x??"").replaceAll('"','""')}"`).join(",")).join("\n"),a=document.createElement("a");a.href=URL.createObjectURL(new Blob([content],{type:"text/csv"}));a.download="alexfisher-members.csv";a.click()}
  return <main className="admin-shell">
    <aside className={mobile?"open":""}><header><Link href="/"><i>AF</i><span>ALEX<strong>FISHER</strong><small>CONTROL CENTER</small></span></Link><button onClick={()=>setMobile(false)}><X/></button></header><nav>{sections.map(([id,label,Icon])=><button key={id} className={section===id?"active":""} onClick={()=>{setSection(id);setMobile(false)}}><Icon/>{label}{id==="members"&&<em>{data.members.length}</em>}</button>)}</nav><footer><Shield/><span><b>Administrator</b><small>Full operations access</small></span><button onClick={()=>db?.auth.signOut()}><LogOut/></button></footer></aside>
    {mobile&&<button className="admin-scrim" onClick={()=>setMobile(false)}/>}<section className="admin-main"><header><button onClick={()=>setMobile(true)}><Menu/></button><div><p>ADMINISTRATION</p><h1>{title}</h1></div><nav><button><Bell/></button><Link href="/account">My account</Link></nav></header>
      {error&&<div className="admin-alert error"><LifeBuoy/>{error}</div>}{notice&&<div className="admin-alert"><CheckCircle2/>{notice}<button onClick={()=>setNotice("")}><X/></button></div>}
      {loading?<div className="admin-loading"><LoaderCircle className="spin"/>Loading control center…</div>:<div className="admin-content">
        {section==="overview"&&<Overview data={data} active={activeSubs.length} expiring={expiring} opted={opted} setSection={setSection}/>} 
        {section==="members"&&<Members rows={filtered} plans={data.plans} search={search} setSearch={setSearch} act={act} busy={busy}/>} 
        {section==="subscriptions"&&<Subscriptions rows={data.subscriptions} members={memberById} act={act} busy={busy}/>} 
        {section==="plans"&&<Plans data={data} act={act} busy={busy}/>} 
        {section==="community"&&<Community rows={data.messages} act={act} busy={busy}/>} 
        {section==="media"&&<Media rows={data.media} act={act} busy={busy}/>} 
        {section==="marketing"&&<Marketing rows={filtered} search={search} setSearch={setSearch} csv={csv} act={act}/>} 
        {section==="audit"&&<Audit rows={data.audit}/>} 
        {section==="settings"&&<AdminSettings/>}
      </div>}
    </section>
  </main>
}

function Overview({data,active,expiring,opted,setSection}:{data:Data;active:number;expiring:number;opted:number;setSection:(s:string)=>void}){const cards=[["Total members",data.members.length,Users,"members"],["Active subscriptions",active,CreditCard,"subscriptions"],["Marketing audience",opted,Mail,"marketing"],["Community posts",data.messages.length,MessageSquare,"community"]] as const;return <><section className="admin-kpis">{cards.map(([label,value,Icon,to])=><button key={label} onClick={()=>setSection(to)}><span><Icon/></span><small>{label}</small><b>{value}</b><em>Open details →</em></button>)}</section><section className="admin-grid"><article className="admin-card"><header><div><p>SUBSCRIPTIONS</p><h2>Renewal watch</h2></div><CreditCard/></header><div className="admin-big"><b>{expiring}</b><span>ending in the next 30 days</span></div><button onClick={()=>setSection("subscriptions")}>Manage subscriptions</button></article><article className="admin-card"><header><div><p>OPERATIONS</p><h2>What needs attention</h2></div><Flag/></header><ul><li><span>Unconfirmed accounts</span><b>{data.members.filter(m=>!m.auth?.confirmed_at).length}</b></li><li><span>Suspended members</span><b>{data.members.filter(m=>m.profiles?.account_status==="suspended").length}</b></li><li><span>Inactive plans</span><b>{data.plans.filter(p=>!p.is_active).length}</b></li><li><span>Uploaded files</span><b>{data.media.length}</b></li></ul></article></section></>}

function Members({rows,plans,search,setSearch,act,busy}:{rows:Row[];plans:Row[];search:string;setSearch:(s:string)=>void;act:(a:string,p?:Row,c?:string)=>void;busy:string}){const[invite,setInvite]=useState(false);return <><div className="admin-tools"><label><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search members or emails"/></label><button onClick={()=>setInvite(true)}><UserPlus/>Invite member</button></div>{invite&&<Invite close={()=>setInvite(false)} act={act}/>}<div className="admin-table"><table><thead><tr><th>Member</th><th>Role</th><th>Access</th><th>Subscription</th><th>Joined</th><th>Actions</th></tr></thead><tbody>{rows.map(m=><tr key={m.user_id}><td><b>{m.profiles?.display_name}</b><small>{m.email}</small></td><td><select value={m.profiles?.role} onChange={e=>act("set_role",{user_id:m.user_id,role:e.target.value})}><option>member</option><option>moderator</option><option>admin</option></select></td><td><button className={m.profiles?.account_status==="suspended"?"pill danger":"pill"} onClick={()=>act("set_account_status",{user_id:m.user_id,status:m.profiles?.account_status==="suspended"?"active":"suspended"},`${m.profiles?.account_status==="suspended"?"Restore":"Suspend"} this member?`)}>{m.profiles?.account_status??"active"}</button></td><td><select value={m.plan} onChange={e=>act("assign_subscription",{user_id:m.user_id,plan_code:e.target.value})}>{plans.map(p=><option key={p.code} value={p.code}>{p.name}</option>)}</select><small>{m.subscription_status}</small></td><td>{date(m.created_at)}</td><td><button className="icon-danger" disabled={busy.includes(m.user_id)} onClick={()=>act("delete_user",{user_id:m.user_id},`Permanently delete ${m.email} and all associated data? This cannot be undone.`)}><Trash2/></button></td></tr>)}</tbody></table></div></>}
function Invite({close,act}:{close:()=>void;act:(a:string,p:Row)=>void}){const[email,setEmail]=useState(""),[name,setName]=useState("");function submit(e:FormEvent){e.preventDefault();act("invite_user",{email,display_name:name});close()}return <form className="admin-inline-form" onSubmit={submit}><div><p>NEW MEMBER</p><h2>Send an email invitation</h2></div><input value={name} onChange={e=>setName(e.target.value)} placeholder="Display name"/><input required type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="name@example.com"/><button>Send invite</button><button type="button" onClick={close}><X/></button></form>}

function Subscriptions({rows,members,act,busy}:{rows:Row[];members:Record<string,Row>;act:(a:string,p?:Row,c?:string)=>void;busy:string}){return <div className="admin-table"><table><thead><tr><th>Member</th><th>Plan</th><th>Status</th><th>Started</th><th>Ends</th><th>Renew</th><th></th></tr></thead><tbody>{rows.map(s=><tr key={s.id}><td><b>{s.profiles?.display_name??members[s.user_id]?.email}</b><small>{members[s.user_id]?.email}</small></td><td>{s.subscription_plans?.name??s.plan_code}<small>{s.duration_months?`${s.duration_months} month${s.duration_months===1?"":"s"}`:"No expiry"}</small></td><td><span className={`status ${s.status}`}>{s.status}</span></td><td>{date(s.starts_at)}</td><td>{date(s.ends_at)}</td><td>{s.auto_renew?"Yes":"No"}</td><td>{["active","trialing"].includes(s.status)&&<button className="text-danger" disabled={busy.includes(s.id)} onClick={()=>act("cancel_subscription",{id:s.id},"Cancel this subscription?")}>Cancel</button>}</td></tr>)}</tbody></table></div>}

function Plans({data,act,busy}:{data:Data;act:(a:string,p?:Row,c?:string)=>void;busy:string}){const[form,setForm]=useState<Row|null>(null);return <><div className="admin-tools"><p>Create any duration now; payment automation can connect later.</p><button onClick={()=>setForm({code:"",name:"",description:"",duration_months:1,price_amount:0,currency:"USD",is_active:false})}><Plus/>New plan</button></div>{form&&<PlanForm value={form} close={()=>setForm(null)} save={p=>{act("save_plan",p);setForm(null)}}/>}<section className="plan-grid">{data.plans.map(p=><article key={p.code}><header><span className={p.is_active?"live":""}>{p.is_active?"ACTIVE":"DRAFT"}</span><button onClick={()=>setForm(p)}>Edit</button></header><h2>{p.name}</h2><p>{p.description}</p><div><b>{p.duration_months||"∞"}</b><small>{p.duration_months?"months":"no expiry"}</small></div><strong>{money(p.price_amount,p.currency)}</strong><fieldset><legend>Included features</legend>{data.features.map(f=>{const on=data.planFeatures.some(x=>x.plan_code===p.code&&x.feature_key===f.feature_key&&x.enabled);return <label key={f.feature_key}><input type="checkbox" checked={on} onChange={e=>act("toggle_plan_feature",{plan_code:p.code,feature_key:f.feature_key,enabled:e.target.checked})}/><span>{f.name}<small>{f.category}</small></span></label>})}</fieldset>{p.code!=="free"&&<button className="delete-plan" disabled={busy.includes(p.code)} onClick={()=>act("delete_plan",{code:p.code},`Delete ${p.name}? Plans assigned to members must be cancelled first.`)}><Trash2/>Delete plan</button>}</article>)}</section><FeatureBuilder act={act}/></>}
function PlanForm({value,close,save}:{value:Row;close:()=>void;save:(v:Row)=>void}){const[v,setV]=useState(value);return <form className="admin-modal" onSubmit={e=>{e.preventDefault();save(v)}}><header><div><p>SUBSCRIPTION PLAN</p><h2>{value.code?"Edit plan":"Create a plan"}</h2></div><button type="button" onClick={close}><X/></button></header><label>Plan name<input required value={v.name} onChange={e=>setV({...v,name:e.target.value,code:v.code||e.target.value.toLowerCase().replace(/[^a-z0-9]+/g,"-")})}/></label><label>Code<input required disabled={Boolean(value.code)} value={v.code} onChange={e=>setV({...v,code:e.target.value})}/></label><label>Description<input value={v.description} onChange={e=>setV({...v,description:e.target.value})}/></label><div><label>Duration (months)<input type="number" min="0" max="120" value={v.duration_months} onChange={e=>setV({...v,duration_months:Number(e.target.value)})}/><small>Use 0 for no expiry.</small></label><label>Price<input type="number" min="0" step="0.01" value={v.price_amount} onChange={e=>setV({...v,price_amount:Number(e.target.value)})}/></label><label>Currency<input maxLength={3} value={v.currency} onChange={e=>setV({...v,currency:e.target.value})}/></label></div><label className="check"><input type="checkbox" checked={v.is_active} onChange={e=>setV({...v,is_active:e.target.checked})}/>Available for assignment</label><footer><button type="button" onClick={close}>Cancel</button><button>Save plan</button></footer></form>}
function FeatureBuilder({act}:{act:(a:string,p:Row)=>void}){const[open,setOpen]=useState(false),[name,setName]=useState(""),[category,setCategory]=useState("General");return <section className="feature-builder"><header><div><p>FUTURE READY</p><h2>Feature catalog</h2><span>Add a future website tool once, then include it in any plan above.</span></div><button onClick={()=>setOpen(!open)}><Plus/>Add feature</button></header>{open&&<form onSubmit={e=>{e.preventDefault();act("save_feature",{feature_key:name,name,category,is_active:true});setName("");setOpen(false)}}><input required value={name} onChange={e=>setName(e.target.value)} placeholder="Feature name"/><input value={category} onChange={e=>setCategory(e.target.value)} placeholder="Category"/><button>Save feature</button></form>}</section>}

function Community({rows,act,busy}:{rows:Row[];act:(a:string,p?:Row,c?:string)=>void;busy:string}){return <section className="moderation-grid">{rows.map(m=><article key={m.id}><header><span>#{m.channel}</span><time>{date(m.created_at)}</time></header><h3>{m.profiles?.display_name??"Deleted member"}</h3><p>{m.content||"Image-only post"}</p><button disabled={busy.includes(m.id)} onClick={()=>act("delete_message",{id:m.id},"Delete this post, its replies, reactions and uploaded files?")}><Trash2/>Delete post</button></article>)}</section>}
function Media({rows,act,busy}:{rows:Row[];act:(a:string,p?:Row,c?:string)=>void;busy:string}){return <section className="media-grid">{rows.map(f=><article key={f.id}><a href={f.public_url} target="_blank"><img src={f.public_url} alt={f.file_name}/></a><div><b>{f.file_name}</b><small>{f.profiles?.display_name??"Member"} · {(f.size_bytes/1024/1024).toFixed(1)} MB</small><button disabled={busy.includes(f.id)} onClick={()=>act("delete_media",{id:f.id,storage_path:f.storage_path},"Permanently delete this uploaded file?")}><Trash2/></button></div></article>)}</section>}
function Marketing({rows,search,setSearch,csv,act}:{rows:Row[];search:string;setSearch:(s:string)=>void;csv:()=>void;act:(a:string,p:Row)=>void}){return <><div className="admin-tools"><label><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search audience"/></label><button onClick={csv}><Download/>Export CSV</button></div><div className="admin-table"><table><thead><tr><th>Contact</th><th>Consent</th><th>Lifecycle</th><th>Last seen</th><th>Joined</th></tr></thead><tbody>{rows.map(m=><tr key={m.user_id}><td><b>{m.profiles?.display_name}</b><small>{m.email}</small></td><td><label className="switch"><input type="checkbox" checked={m.marketing_consent} onChange={e=>act("update_contact",{user_id:m.user_id,lifecycle_stage:m.lifecycle_stage,marketing_consent:e.target.checked})}/><span/></label></td><td><select value={m.lifecycle_stage} onChange={e=>act("update_contact",{user_id:m.user_id,lifecycle_stage:e.target.value,marketing_consent:m.marketing_consent})}><option>member</option><option>lead</option><option>customer</option><option>vip</option><option>churned</option></select></td><td>{date(m.last_seen_at)}</td><td>{date(m.created_at)}</td></tr>)}</tbody></table></div></>}
function Audit({rows}:{rows:Row[]}){return <div className="audit-list">{rows.map(r=><article key={r.id}><span><Archive/></span><div><b>{r.action.replaceAll("_"," ")}</b><p>{r.profiles?.display_name??"System"} · {r.entity_type}{r.entity_id?` · ${r.entity_id.slice(0,12)}`:""}</p></div><time>{new Date(r.created_at).toLocaleString()}</time></article>)}</div>}
function AdminSettings(){return <section className="settings-grid"><article><Shield/><h2>Security model</h2><p>Every operation re-checks your live Supabase session and administrator role on the server. The private administration key is never sent to the browser.</p></article><article><CreditCard/><h2>Payments</h2><p>Plans and manual subscriptions are ready. Before charging customers, connect Stripe webhooks, tax settings, invoices, refunds and Terms.</p></article><article><Mail/><h2>Email delivery</h2><p>Connect a branded SMTP provider before inviting a large audience so confirmations and password recovery remain reliable.</p></article><article><BarChart3/><h2>Scale</h2><p>Monitor database, storage, realtime connections, email limits and costs as membership grows. Upgrade infrastructure before reaching free-plan limits.</p></article><aside><h2>Technical consoles</h2><a target="_blank" href="https://supabase.com/dashboard/project/dlbzlclexpbmzoehtioa">Open Supabase</a><a target="_blank" href="https://vercel.com/khaledelkafouri-9403/alex-fisher">Open Vercel</a></aside></section>}
