"use client";
/* eslint-disable @typescript-eslint/no-explicit-any */

import Link from "next/link";
import "./classroom.css";
import {useEffect,useRef,useState} from "react";
import {ArrowLeft,ArrowRight,BookOpen,Check,CheckCircle2,CircleDot,Clock3,FileText,Fish,Languages,Layers3,ListChecks,Lock,NotebookPen,Play,PlayCircle,Ruler,Sparkles,Waves} from "lucide-react";
import {CourseNavigation,CourseProgress} from "./course-navigation";
import {createSupabaseClient} from "@/lib/supabase/client";

type Language="en"|"ar";
type CourseId=string;
type Resource={id:string;title:string;url?:string;resource_type:string};
type Lesson={id:string;en:string;ar:string;minutes:number;preview?:boolean;video_provider?:string;video_url?:string;video_id?:string;resources?:Resource[]};
type Section={en:string;ar:string;lessons:Lesson[]};
type Course={id:CourseId;icon:typeof Ruler;tone:string;en:string;ar:string;enDesc:string;arDesc:string;level:string;sections:Section[]};
const lesson=(id:string,en:string,ar:string,minutes:number,preview=false):Lesson=>({id,en,ar,minutes,preview});
const fallbackCourses:Course[]=[
  {id:"rods",icon:Ruler,tone:"coral",en:"Fishing Rods",ar:"قصبات الصيد",enDesc:"Choose the right length, power, action and casting weight.",arDesc:"اختار الطول والقوة والأكشن ووزن الرمي المناسب.",level:"Beginner",sections:[
    {en:"Start with the rod",ar:"ابدأ مع القصبة",lessons:[lesson("rod-1","Rod parts and terminology","أجزاء القصبة والمصطلحات",8,true),lesson("rod-2","Length and casting distance","الطول ومسافة الرمي",11),lesson("rod-3","Read casting-weight ratings","قراءة وزن الرمي المكتوب",9)]},
    {en:"Power and action",ar:"القوة والأكشن",lessons:[lesson("rod-4","Power versus action","الفرق بين القوة والأكشن",12),lesson("rod-5","Fast, moderate and slow action","الأكشن السريع والمتوسط والبطيء",10),lesson("rod-6","Match a rod to your style","طابق القصبة مع طريقة الصيد",14)]},
    {en:"Setup and care",ar:"التجهيز والعناية",lessons:[lesson("rod-7","Balance rod, reel and line","وازن القصبة والماكينة والخيط",13),lesson("rod-8","Saltwater cleaning and storage","التنظيف والتخزين بعد البحر",7)]}]},
  {id:"reels",icon:CircleDot,tone:"cyan",en:"Fishing Reels",ar:"ماكينات الصيد",enDesc:"Select, set up and maintain the right reel for the job.",arDesc:"اختار ماكينة الصيد المناسبة، جهزها وحافظ عليها.",level:"Beginner",sections:[
    {en:"Reel foundations",ar:"أساسيات الماكينة",lessons:[lesson("reel-1","Reel types explained","شرح أنواع ماكينات الصيد",9,true),lesson("reel-2","Reel size and line capacity","حجم الماكينة وسعة الخيط",12),lesson("reel-3","Gear ratio made simple","شرح نسبة التروس ببساطة",8)]},
    {en:"Set up correctly",ar:"التجهيز الصحيح",lessons:[lesson("reel-4","Spool line without twist","ملء الخيط بدون التفاف",13),lesson("reel-5","Set the drag correctly","ضبط الفرامل بشكل صحيح",11),lesson("reel-6","Balance reel and rod","وازن الماكينة مع القصبة",9)]},
    {en:"Care and troubleshooting",ar:"العناية وحل المشاكل",lessons:[lesson("reel-7","Clean after saltwater use","التنظيف بعد استخدام البحر",8),lesson("reel-8","Fix common reel problems","حل مشاكل الماكينة الشائعة",14)]}]},
  {id:"hooks",icon:Fish,tone:"mint",en:"Hooks",ar:"السنار",enDesc:"Match hook shape, size and strength to bait and target fish.",arDesc:"طابق شكل وحجم وقوة السن مع الطُعم والسمكة.",level:"Beginner",sections:[
    {en:"Know your hook",ar:"اعرف السنار",lessons:[lesson("hook-1","Hook anatomy and sizes","أجزاء السن ومقاساته",8,true),lesson("hook-2","J-hooks and circle hooks","السن العادي والسن الدائري",10),lesson("hook-3","Wire gauge and strength","سمك السلك والقوة",7)]},
    {en:"Match hook to bait",ar:"طابق السن مع الطُعم",lessons:[lesson("hook-4","Natural bait presentation","تقديم الطُعم الطبيعي",13),lesson("hook-5","Assist hooks for jigs","السنار المساعد للجيج",11),lesson("hook-6","Treble hooks and lures","السن الثلاثي والطعوم",9)]},
    {en:"Hook and land fish",ar:"تثبيت وإخراج السمكة",lessons:[lesson("hook-7","Sharpness and hook-set timing","حدة السن وتوقيت الشد",12),lesson("hook-8","Safe unhooking and release","فك السن وإعادة السمكة بأمان",8)]}]},
  {id:"lures",icon:Sparkles,tone:"gold",en:"Lures & Jigs",ar:"الطعوم والجيج",enDesc:"Choose lure type, colour, depth and retrieve for the conditions.",arDesc:"اختار النوع واللون والعمق وطريقة السحب حسب الظروف.",level:"Intermediate",sections:[
    {en:"Build your lure box",ar:"جهز علبة الطعوم",lessons:[lesson("lure-1","Hard lures, plastics and jigs","الطعوم الصلبة والسيليكون والجيج",12,true),lesson("lure-2","Profile, size and target fish","الشكل والحجم والسمكة",10),lesson("lure-3","Choose lure colour","اختيار لون الطُعم",9)]},
    {en:"Fish the water column",ar:"اصطاد طبقات المياه",lessons:[lesson("lure-4","Surface, midwater and bottom","السطح ومنتصف المياه والقاع",14),lesson("lure-5","Weight, depth and current","الوزن والعمق والتيار",12),lesson("lure-6","Read lure action","فهم حركة الطُعم",8)]},
    {en:"Retrieve with purpose",ar:"اسحب الطُعم بذكاء",lessons:[lesson("lure-7","Speed, pauses and cadence","السرعة والتوقف والإيقاع",13),lesson("lure-8","Change tactics when fish do not bite","غير خطتك عندما لا يعض السمك",11)]}]},
  {id:"braid",icon:Layers3,tone:"blue",en:"Braided Line",ar:"الخيط المجدول",enDesc:"Understand PE rating, strength, leaders, knots and spool setup.",arDesc:"افهم تصنيف PE والقوة والليدر والعُقد وتجهيز البكرة.",level:"Intermediate",sections:[
    {en:"Choose your braid",ar:"اختار الخيط المجدول",lessons:[lesson("braid-1","Diameter, PE and strand count","القطر وتصنيف PE وعدد الخيوط",11,true),lesson("braid-2","Strength and target species","القوة والسمك المستهدف",9),lesson("braid-3","Colour and line marking","اللون وعلامات الخيط",7)]},
    {en:"Spool and connect",ar:"املأ البكرة واربط",lessons:[lesson("braid-4","Backing and spool filling","الباكينج وملء البكرة",13),lesson("braid-5","Connect braid to leader","ربط الخيط بالليدر",15),lesson("braid-6","Reliable terminal knots","عُقد نهائية موثوقة",12)]},
    {en:"Cast and maintain",ar:"الرمي والصيانة",lessons:[lesson("braid-7","Prevent wind knots and tangles","منع عُقد الهواء والتشابك",10),lesson("braid-8","Inspect, reverse and replace","فحص وعكس وتغيير الخيط",8)]}]},
];

export default function LearningPage(){
  const[language,setLanguage]=useState<Language>("en"),[selected,setSelected]=useState<CourseId>("rods"),[activeLesson,setActiveLesson]=useState("rod-1"),[,setOpenSections]=useState<number[]>([0]),[completed,setCompleted]=useState<string[]>([]),[tab,setTab]=useState("overview"),[managedCourses,setManagedCourses]=useState<Course[]>([]),[token,setToken]=useState(""),[mobileCurriculumOpen,setMobileCurriculumOpen]=useState(false),[sidebarVisible,setSidebarVisible]=useState(true),[pending,setPending]=useState<string[]>([]),[progressError,setProgressError]=useState("");
  const stageRef=useRef<HTMLDivElement>(null);
  const savingLessons=useRef(new Set<string>());
  const courseList=managedCourses.length?managedCourses:fallbackCourses,rtl=language==="ar",course=courseList.find(item=>item.id===selected)??courseList[0],lessons=course.sections.flatMap(section=>section.lessons),current=lessons.find(item=>item.id===activeLesson)??lessons[0],currentIndex=Math.max(0,lessons.findIndex(item=>item.id===current?.id)),done=lessons.filter(item=>completed.includes(item.id)).length,progress=lessons.length?Math.round(done/lessons.length*100):0;
  useEffect(()=>{const db=createSupabaseClient();db?.auth.getSession().then(async({data:{session}})=>{if(!session?.access_token)return;setToken(session.access_token);const response=await fetch("/api/learning",{cache:"no-store",headers:{Authorization:`Bearer ${session.access_token}`}});if(!response.ok)return;const data=await response.json(),icons:Record<string,typeof Ruler>={rods:Ruler,reels:CircleDot,hooks:Fish,lures:Sparkles,braid:Layers3},tones:Record<string,string>={rods:"coral",reels:"cyan",hooks:"mint",lures:"gold",braid:"blue"};const mapped:Course[]=data.courses.map((item:Record<string,any>)=>({id:item.slug,icon:icons[item.slug]??BookOpen,tone:tones[item.slug]??"cyan",en:item.title_en,ar:item.title_ar,enDesc:item.description_en,arDesc:item.description_ar,level:item.level,sections:item.sections.map((section:Record<string,any>)=>({en:section.title_en,ar:section.title_ar,lessons:section.lessons.map((entry:Record<string,any>)=>({id:entry.id,en:entry.title_en,ar:entry.title_ar,minutes:Number(entry.duration_minutes||0),preview:entry.is_preview,video_provider:entry.video_provider,video_url:entry.video_url,video_id:entry.video_id,resources:entry.resources}))}))})).filter((item:Course)=>item.sections.some(section=>section.lessons.length)),completedIds:string[]=data.progress.filter((item:Record<string,any>)=>item.completed).map((item:Record<string,any>)=>item.lesson_id);if(mapped.length){setManagedCourses(mapped);setSelected(mapped[0].id);const available=mapped[0].sections.flatMap(section=>section.lessons),resume=available.find(item=>!completedIds.includes(item.id))??available[0];if(resume)setActiveLesson(resume.id);const resumeSection=mapped[0].sections.findIndex(section=>section.lessons.some(item=>item.id===resume?.id));setOpenSections([Math.max(0,resumeSection)])}setCompleted(completedIds)})},[]);
  function chooseLesson(id:string,sectionIndex?:number,courseId=course.id){setSelected(courseId);setActiveLesson(id);setTab("overview");if(sectionIndex!==undefined)setOpenSections([sectionIndex]);setMobileCurriculumOpen(false);requestAnimationFrame(()=>stageRef.current?.scrollIntoView({behavior:"smooth",block:"start"}))}
  async function toggleComplete(id:string){
    if(savingLessons.current.has(id))return;
    if(!token){setProgressError(rtl?"سجل الدخول لحفظ تقدمك.":"Sign in to save your progress.");return}
    savingLessons.current.add(id);setPending(items=>[...items,id]);setProgressError("");
    const next=!completed.includes(id);
    try{const response=await fetch("/api/learning",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${token}`},body:JSON.stringify({lesson_id:id,completed:next})});if(!response.ok)throw new Error("save failed");setCompleted(items=>next?[...new Set([...items,id])]:items.filter(item=>item!==id))}
    catch{setProgressError(rtl?"تعذر حفظ التقدم. حاول مرة أخرى.":"We couldn't save your progress. Please try again.")}
    finally{savingLessons.current.delete(id);setPending(items=>items.filter(item=>item!==id))}
  }
  function moveLesson(offset:number){const next=lessons[currentIndex+offset];if(!next)return;const sectionIndex=course.sections.findIndex(section=>section.lessons.some(item=>item.id===next.id));chooseLesson(next.id,sectionIndex)}
  return <main dir={rtl?"rtl":"ltr"} className={`learning-page academy-page ${rtl?"font-arabic":""}`}>
    <header className="learning-topbar classroom-topbar"><Link className="brand" href="/"><span className="brand-mark"><Waves/></span><span>ALEX<strong>FISHER</strong><small>ACADEMY</small></span></Link><span className="classroom-course-title">{rtl?course.ar:course.en}</span><nav><CourseProgress courses={courseList} selected={course.id} completed={completed} rtl={rtl} pending={pending.length>0}/><button className="mobile-curriculum-toggle" onClick={()=>{setSidebarVisible(true);setMobileCurriculumOpen(true)}} aria-label={rtl?"فتح محتوى الكورسات":"Open course content"}><ListChecks/>{rtl?"محتوى الكورس":"Course content"}</button><button className="language-button" onClick={()=>setLanguage(rtl?"en":"ar")}><Languages/>{rtl?"EN":"العربية"}</button><Link href="/" className="classroom-exit"><ArrowLeft/>{rtl?"خروج":"Exit"}</Link></nav></header>
    <section className="academy-course">
      <div className={`academy-player ${sidebarVisible?"":"sidebar-hidden"}`}>
        <div className="lesson-stage" ref={stageRef}>
          <div className="lesson-video" key={current.id}>{current.video_url||current.video_id?<LessonVideo lesson={current}/>:<><span><Play/></span><small>{rtl?"فيديو الدرس":"LESSON VIDEO"}</small><h2>{rtl?current.ar:current.en}</h2><p>{rtl?"سيظهر فيديو AlexFisher هنا بمجرد نشر محتوى هذا الدرس.":"Your AlexFisher video will appear here when this lesson is published."}</p></>}</div>
          <div className="lesson-now-playing"><span>{rtl?`الدرس ${currentIndex+1} من ${lessons.length}`:`Lesson ${currentIndex+1} of ${lessons.length}`}</span><b>{rtl?current.ar:current.en}</b><button className="lesson-content-button" onClick={()=>setMobileCurriculumOpen(true)}><ListChecks/>{rtl?"محتوى الكورس":"Course content"}</button></div>
          <nav>{[["overview",rtl?"نظرة عامة":"Overview"],["notes",rtl?"ملاحظاتي":"My notes"],["resources",rtl?"المصادر":"Resources"]].map(([id,label])=><button key={id} className={tab===id?"active":""} onClick={()=>setTab(id)}>{label}</button>)}</nav>
          <div className="lesson-information">{tab==="overview"&&<><p>{rtl?"عن هذا الدرس":"ABOUT THIS LESSON"}</p><h3>{rtl?current.ar:current.en}</h3><span>{rtl?course.arDesc:course.enDesc}</span><div><Clock3/>{current.minutes} {rtl?"دقيقة":"minutes"}<Sparkles/>{course.level}</div></>}{tab==="notes"&&<><p>{rtl?"ملاحظاتي":"MY NOTES"}</p><h3>{rtl?"احتفظ بأهم النقاط":"Keep the important ideas close"}</h3><span>{rtl?"ستتمكن من حفظ ملاحظات مرتبطة بكل درس.":"You will be able to save notes connected to each lesson."}</span><button><NotebookPen/>{rtl?"الملاحظات قريباً":"Notes coming soon"}</button></>}{tab==="resources"&&<><p>{rtl?"مصادر الدرس":"LESSON RESOURCES"}</p><h3>{rtl?"ملفات وروابط مفيدة":"Useful files and links"}</h3>{current.resources?.length?<div className="lesson-resource-links">{current.resources.map(resource=><a key={resource.id} href={resource.url} target="_blank" rel="noreferrer"><FileText/>{resource.title}</a>)}</div>:<><span>{rtl?"لا توجد ملفات مرفقة بهذا الدرس بعد.":"No files are attached to this lesson yet."}</span><button><Lock/>{rtl?"لا توجد مصادر بعد":"No resources yet"}</button></>}</>}</div>
          {progressError&&<p className="lesson-progress-error" role="alert">{progressError}</p>}
          <div className="lesson-navigation">
            <button onClick={()=>moveLesson(-1)} disabled={currentIndex===0}><ArrowLeft/>{rtl?"السابق":"Previous"}</button>
            <button className={`complete-lesson ${completed.includes(current.id)?"completed":""}`} onClick={()=>toggleComplete(current.id)} disabled={pending.includes(current.id)}>{completed.includes(current.id)?<CheckCircle2/>:<Check/>}{completed.includes(current.id)?(rtl?"تم إكمال الدرس":"Lesson completed"):(rtl?"وضع علامة مكتمل":"Mark as complete")}</button>
            <button onClick={()=>moveLesson(1)} disabled={currentIndex===lessons.length-1}>{rtl?"التالي":"Next"}<ArrowRight/></button>
          </div>
          {progress===100&&<div className="course-complete"><CheckCircle2/><span><b>{rtl?"أكملت هذا الكورس!":"Course complete!"}</b><small>{rtl?"عمل رائع — تم حفظ تقدمك.":"Great work — your progress is saved."}</small></span></div>}
        </div>
        <CourseNavigation courses={courseList} selected={course.id} activeLesson={current.id} completed={completed} pending={pending} rtl={rtl} open={mobileCurriculumOpen} onOpenChange={setMobileCurriculumOpen} desktopOpen={sidebarVisible} onDesktopOpenChange={setSidebarVisible} onChoose={(courseId,lessonId)=>chooseLesson(lessonId,undefined,courseId)} onComplete={toggleComplete}/>
      </div>
    </section>

  </main>
}

function youtubeId(value:string){const raw=value.trim();if(/^[a-zA-Z0-9_-]{11}$/.test(raw))return raw;try{const url=new URL(raw),host=url.hostname.replace(/^www\./,"");if(host==="youtu.be")return url.pathname.split("/").filter(Boolean)[0]||"";if(host.endsWith("youtube.com")){if(url.searchParams.get("v"))return url.searchParams.get("v")||"";const parts=url.pathname.split("/").filter(Boolean);if(["embed","shorts","live"].includes(parts[0]))return parts[1]||""}}catch{return ""}return ""}
function LessonVideo({lesson}:{lesson:Lesson}){const raw=(lesson.video_url||lesson.video_id||"").trim(),savedProvider=lesson.video_provider||"external",provider=/youtu(?:\.be|be\.com)/i.test(raw)?"youtube":/vimeo\.com/i.test(raw)?"vimeo":savedProvider;if(provider==="youtube"){const id=youtubeId(raw);if(!id)return <div className="video-notice"><PlayCircle/><b>This YouTube link could not be read</b><span>Edit the lesson and paste the normal YouTube Share link or the 11-character video ID.</span></div>;return <iframe className="lesson-embed" src={`https://www.youtube-nocookie.com/embed/${id}?rel=0`} title={lesson.en} allow="accelerometer; autoplay; encrypted-media; picture-in-picture" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen/>}if(provider==="vimeo"){const id=raw.match(/vimeo\.com\/(?:video\/)?(\d+)/)?.[1]||(/^[0-9]+$/.test(raw)?raw:"");if(!id)return <div className="video-notice"><PlayCircle/><b>This Vimeo link could not be read</b><span>Paste the Vimeo share link or numeric video ID.</span></div>;return <iframe className="lesson-embed" src={`https://player.vimeo.com/video/${id}`} title={lesson.en} allow="autoplay; fullscreen; picture-in-picture" allowFullScreen/>}if(provider==="cloudflare_stream"){const src=raw.startsWith("http")?raw:`https://iframe.videodelivery.net/${raw}`;return <iframe className="lesson-embed" src={src} title={lesson.en} allow="accelerometer; autoplay; encrypted-media; picture-in-picture" allowFullScreen/>}if(provider==="mux"&&!raw.startsWith("http"))return <div className="video-notice"><PlayCircle/><b>Mux playback ID saved</b><span>Paste a complete embeddable URL until the dedicated Mux player is connected.</span></div>;if(/\.(mp4|webm|ogg)(?:\?|$)/i.test(raw))return <video className="lesson-direct-video" src={raw} controls preload="metadata"/>;return <iframe className="lesson-embed" src={raw} title={lesson.en} allow="accelerometer; autoplay; encrypted-media; picture-in-picture" allowFullScreen/>}
