"use client";
import Link from "next/link";
import { useSearchParams } from "next/navigation";
import { FormEvent,Suspense,useMemo,useState } from "react";
import { Anchor,Check,LoaderCircle,LockKeyhole,Mail,UserRound } from "lucide-react";
import { createSupabaseClient } from "@/lib/supabase/client";
import {safeNext} from "@/lib/auth-navigation";
function Form(){const query=useSearchParams(),supabase=useMemo(()=>createSupabaseClient(),[]);const[mode,setMode]=useState<"signup"|"signin">(query.get("mode")==="signin"?"signin":"signup"),[name,setName]=useState(""),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[marketing,setMarketing]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(query.has("error")?"The email link has expired or could not be verified. Request a new link and open it in this same browser.":"");const next=safeNext(query.get("next"));
async function submit(e:FormEvent){e.preventDefault();if(!supabase){setMessage("Connect your Supabase project to activate membership.");return}setBusy(true);setMessage("");if(mode==="signup"){const{data,error}=await supabase.auth.signUp({email,password,options:{emailRedirectTo:`${location.origin}/auth/callback?next=${encodeURIComponent(next)}`,data:{display_name:name.trim(),marketing_consent:marketing}}});if(error)setMessage(error.message);else if(data.session)location.assign(next);else setMessage("Check your email and confirm your account to continue.")}else{const{error}=await supabase.auth.signInWithPassword({email,password});if(error)setMessage(error.message);else location.assign(next)}setBusy(false)}
async function reset(){if(busy)return;if(!supabase){setMessage("Password recovery is unavailable. Please try again later.");return}if(!/^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$/.test(email.trim())){setMessage("Enter a valid email address first.");return}setBusy(true);setMessage("");try{const{error}=await supabase.auth.resetPasswordForEmail(email.trim(),{redirectTo:`${location.origin}/auth/callback?next=/auth/reset-password`});if(error)throw error;setMessage("If an account exists for this email, a reset link will be sent. Check spam and open the newest link in this same browser. If no email arrives, contact the site administrator to check email delivery.");}catch(error){setMessage(error instanceof Error?error.message:"Could not request a reset. Please try again.");}finally{setBusy(false)}}
return <main className="login-page"><section className="login-story"><Link href="/" className="login-brand"><i><Anchor/></i>ALEX<strong>FISHER</strong></Link><div><p>YOUR SEA · YOUR CREW</p><h1>Better days on the water start here.</h1><span>One free account unlocks conditions, planning tools and conversations with people who share your water.</span></div><ul><li><Check/>All marine tools</li><li><Check/>Three activity communities</li><li><Check/>Secure member profile</li></ul></section><section className="login-panel"><div className="login-card"><nav><button className={mode==="signup"?"active":""} onClick={()=>setMode("signup")}>Create account</button><button className={mode==="signin"?"active":""} onClick={()=>setMode("signin")}>Sign in</button></nav><h2>{mode==="signup"?"Join AlexFisher free":"Welcome back"}</h2><p>{mode==="signup"?"Start free. Paid plans may be offered later.":"Sign in to continue."}</p><form onSubmit={submit}>{mode==="signup"&&<label><span>Display name</span><div><UserRound/><input value={name} onChange={e=>setName(e.target.value)} minLength={2} maxLength={50} required placeholder="How members see you"/></div></label>}<label><span>Email address</span><div><Mail/><input type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} required placeholder="you@example.com"/></div></label><label><span>Password</span><div><LockKeyhole/><input type="password" autoComplete={mode==="signup"?"new-password":"current-password"} value={password} onChange={e=>setPassword(e.target.value)} minLength={8} required placeholder="At least 8 characters"/></div></label>{mode==="signup"&&<label className="marketing-opt"><input type="checkbox" checked={marketing} onChange={e=>setMarketing(e.target.checked)}/><span><b>Send me useful AlexFisher updates</b><small>Optional product news, guidance and offers. Unsubscribe anytime.</small></span></label>}{message&&<output>{message}</output>}<button className="login-submit" disabled={busy}>{busy?<LoaderCircle className="spin"/>:mode==="signup"?"Create free account":"Sign in with email"}</button></form>{mode==="signin"&&<button className="forgot" disabled={busy} onClick={reset}>Forgot password?</button>}<small className="login-legal">By joining, you accept responsible community participation and our <Link href="/privacy">privacy notice</Link>.</small></div></section></main>}
export default function LoginPage(){return <Suspense><Form/></Suspense>}
