"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { AlertTriangle, ArrowLeft, ArrowRight, Camera, Check, ChevronRight, Compass, Fish, Image as ImageIcon, Languages, Layers3, Map, MapPin, RefreshCw, Save, ScanLine, ShieldAlert, Sparkles, Target, UploadCloud, Waves, Wind } from "lucide-react";

type Language = "en" | "ar";
type Zone = { id:string; x:number; y:number; tone:"primary"|"secondary"|"search"|"danger"; title:string; reason:string; cast:string; distance:string; column:string; lure:string; retrieve:string; risk:string };
type LiveConditions = { city?:string; spot?:string; wind:number; gust:number; tideState:string; tide:number; updatedAt?:string };
type Cell = { x:number; y:number; lum:number; texture:number };

const styles = [["casting","Casting / Spinning","كاستنج / سبيننج"],["shore-jig","Shore Jigging","شور جيجنج"],["surf","Surf Fishing","صيد الشاطئ"],["popping","Popping","بوبنج"],["unsure","Not sure","غير متأكد"]];
const fish = [["unsure","Not sure — recommend targets","غير متأكد — اقترح أسماكاً"],["bluefish","Bluefish","مياس"],["barracuda","Barracuda","باراكودا"],["needlefish","Needlefish","خرمان"],["seabass","Sea Bass","قاروص"],["seabream","Sea Bream","دنيس"],["mormora","Mormora","مرمار"],["bonito","Bonito","بلاميطة"],["mackerel","Mackerel","ماكريل"],["leerfish","Leerfish","ليتشة"],["grouper","Grouper","هامور"],["amberjack","Amberjack","أمبرجاك"],["mahi","Mahi Mahi","ماهي ماهي"],["gt","GT","جي تي"],["queenfish","Queenfish","كوين فيش"],["tuna","Tuna","تونة"],["other","Other","أخرى"]];
const spotTypes = [["auto","Not sure / auto","غير متأكد / تلقائي"],["rocks","Rocky shore / ledge","شاطئ صخري / حافة"],["breakwater","Breakwater / jetty","حاجز أمواج / لسان"],["beach","Sandy beach","شاطئ رملي"],["harbour","Harbour / pier","ميناء / رصيف"],["reef","Reef / mixed bottom","شعاب / قاع مختلط"],["satellite","Satellite / map screenshot","صورة قمر صناعي / خريطة"]];
const tideOptions = [["live","Use current conditions","استخدم الظروف الحالية"],["low","Low","جزر"],["rising","Rising","صاعد"],["high","High","مد عالٍ"],["falling","Falling","هابط"],["unknown","Unknown","غير معروف"]];
const windOptions = [["live","Use live wind","استخدم الرياح المباشرة"],["calm","Calm","هادئة"],["light","Light","خفيفة"],["moderate","Moderate","متوسطة"],["strong","Strong","قوية"],["unknown","Unknown","غير معروف"]];

function ChoiceGrid({items,value,onChange,rtl}:{items:string[][];value:string;onChange:(value:string)=>void;rtl:boolean}){
  return <div className="spot-choice-grid">{items.map(([id,en,ar])=><button type="button" key={id} className={value===id?"selected":""} onClick={()=>onChange(id)}><span>{rtl?ar:en}</span>{value===id&&<Check size={16}/>}</button>)}</div>;
}

async function scanPhoto(file:File){
  const bitmap=await createImageBitmap(file);
  const max=480, scale=Math.min(1,max/Math.max(bitmap.width,bitmap.height));
  const width=Math.max(1,Math.round(bitmap.width*scale)), height=Math.max(1,Math.round(bitmap.height*scale));
  const canvas=document.createElement("canvas"); canvas.width=width; canvas.height=height;
  const ctx=canvas.getContext("2d",{willReadFrequently:true}); if(!ctx)throw new Error("Canvas unavailable");
  ctx.drawImage(bitmap,0,0,width,height); const data=ctx.getImageData(0,0,width,height).data;
  const cols=5,rows=4,cells:Cell[]=[];
  for(let row=0;row<rows;row++)for(let col=0;col<cols;col++){
    const x0=Math.floor(col*width/cols),x1=Math.floor((col+1)*width/cols),y0=Math.floor(row*height/rows),y1=Math.floor((row+1)*height/rows);
    let lum=0,texture=0,count=0;
    for(let y=y0+2;y<y1-2;y+=4)for(let x=x0+2;x<x1-2;x+=4){const i=(y*width+x)*4,j=(y*width+Math.min(width-1,x+4))*4;const a=data[i]*.2126+data[i+1]*.7152+data[i+2]*.0722;const b=data[j]*.2126+data[j+1]*.7152+data[j+2]*.0722;lum+=a;texture+=Math.abs(a-b);count++;}
    cells.push({x:(col+.5)*100/cols,y:(row+.5)*100/rows,lum:lum/Math.max(1,count),texture:texture/Math.max(1,count)});
  }
  bitmap.close();
  const chosen:Cell[]=[]; const pick=(list:Cell[])=>list.find(cell=>chosen.every(other=>Math.hypot(cell.x-other.x,cell.y-other.y)>22))??list[0];
  const dark=pick([...cells].sort((a,b)=>a.lum-b.lum)); chosen.push(dark);
  const edge=pick([...cells].sort((a,b)=>b.texture-a.texture)); chosen.push(edge);
  const open=pick([...cells].filter(c=>c.y>25).sort((a,b)=>a.texture-b.texture)); chosen.push(open);
  const snag=pick([...cells].filter(c=>c!==edge).sort((a,b)=>b.texture-a.texture));
  const thumb=document.createElement("canvas"); thumb.width=Math.max(1,Math.round(width*Math.min(1,640/width)));thumb.height=Math.max(1,Math.round(height*Math.min(1,640/height)));thumb.getContext("2d")?.drawImage(canvas,0,0,thumb.width,thumb.height);
  return {cells:{dark,edge,open,snag},thumbnail:thumb.toDataURL("image/jpeg",.68)};
}

export default function ReadMySpotPage(){
  const [language,setLanguage]=useState<Language>("en"); const rtl=language==="ar"; const t=(en:string,ar:string)=>rtl?ar:en;
  const [stage,setStage]=useState<"upload"|"context"|"result">("upload"); const [file,setFile]=useState<File|null>(null); const [preview,setPreview]=useState(""); const [thumbnail,setThumbnail]=useState("");
  const [style,setStyle]=useState("unsure"),[target,setTarget]=useState("unsure"),[spotType,setSpotType]=useState("auto"),[tide,setTide]=useState("live"),[wind,setWind]=useState("live");
  const [live,setLive]=useState<LiveConditions|null>(null),[zones,setZones]=useState<Zone[]>([]),[activeZone,setActiveZone]=useState("A"),[scanning,setScanning]=useState(false),[saved,setSaved]=useState(false),[error,setError]=useState("");
  const cameraRef=useRef<HTMLInputElement>(null),uploadRef=useRef<HTMLInputElement>(null);
  useEffect(()=>{const savedLanguage=localStorage.getItem("alexfisher-language");if(savedLanguage==="ar"||savedLanguage==="en")setLanguage(savedLanguage);try{const raw=localStorage.getItem("alexfisher-current-conditions");if(raw)setLive(JSON.parse(raw));else{setTide("unknown");setWind("unknown");}}catch{setTide("unknown");setWind("unknown");}},[]);
  useEffect(()=>()=>{if(preview)URL.revokeObjectURL(preview)},[preview]);
  const toggleLanguage=()=>{const next=rtl?"en":"ar";setLanguage(next);localStorage.setItem("alexfisher-language",next)};

  const handleFile=(next?:File)=>{if(!next)return;if(!next.type.startsWith("image/")){setError(t("Please choose an image file.","اختر ملف صورة."));return}if(next.size>15*1024*1024){setError(t("Please use an image smaller than 15 MB.","استخدم صورة أقل من 15 ميجابايت."));return}if(preview)URL.revokeObjectURL(preview);setFile(next);setPreview(URL.createObjectURL(next));setError("");setSaved(false)};
  const beginContext=()=>{if(file)setStage("context")};

  const analysisProfile=useMemo(()=>{
    const rocky=["rocks","breakwater","reef","harbour"].includes(spotType); const sandy=spotType==="beach"; const harshWind=wind==="strong"||(wind==="live"&&(live?.wind??0)>=22); const highWater=tide==="high";
    const resolvedStyle=style!=="unsure"?style:sandy?"surf":rocky?"shore-jig":"casting";
    const suggestedTargets=sandy?[["Sea Bream","دنيس"],["Mormora","مرمار"],["Sea Bass","قاروص"]]:spotType==="reef"?[["Grouper","هامور"],["Snapper","نهاش"],["Barracuda","باراكودا"]]:[["Bluefish","مياس"],["Barracuda","باراكودا"],["Bonito","بلاميطة"],["Needlefish","خرمان"]];
    const lure=resolvedStyle==="shore-jig"?t("30–40 g rear-weighted metal jig","جيج معدني 30–40 جم بوزن خلفي"):resolvedStyle==="popping"?t("Medium popper or floating stickbait","بوبر متوسط أو ستيك بيت عائم"):resolvedStyle==="surf"?t("Slim metal lure or sinking pencil; bait rig is also worth trying","طُعم معدني انسيابي أو سنكنج بنسل؛ ويمكن تجربة عدة الطُعم"):t("Sinking minnow or sinking pencil","مينو غاطس أو سنكنج بنسل");
    return {rocky,sandy,harshWind,highWater,resolvedStyle,suggestedTargets,lure};
  },[spotType,style,target,tide,wind,live,rtl]);

  const analyse=async()=>{if(!file)return;setScanning(true);setError("");try{const scan=await scanPhoto(file);setThumbnail(scan.thumbnail);const risk=analysisProfile.rocky?t("High","مرتفع"):analysisProfile.sandy?t("Low–medium","منخفض–متوسط"):t("Medium","متوسط");setZones([
    {id:"A",x:scan.cells.edge.x,y:scan.cells.edge.y,tone:"primary",title:t("Best first cast","أفضل رمية أولى"),reason:t("A visible contrast/structure edge is worth testing first. Fish often use edges instead of featureless water.","حافة التباين أو البنية الظاهرة تستحق التجربة أولاً؛ فالأسماك غالباً تستخدم الحواف بدلاً من المياه المفتوحة بلا معالم."),cast:analysisProfile.rocky?t("Cast slightly beyond the edge and retrieve parallel to it.","ارمِ بعد الحافة قليلاً واسترجع الطُعم بمحاذاتها."):t("Cast across the visible transition and retrieve through it.","ارمِ عبر منطقة الانتقال الظاهرة واسترجع الطُعم خلالها."),distance:t("Medium cast","رمية متوسطة"),column:t("Upper to mid-water","أعلى إلى منتصف المياه"),lure:analysisProfile.lure,retrieve:t("Medium-fast","متوسط إلى سريع"),risk:analysisProfile.rocky?t("Medium–high","متوسط–مرتفع"):t("Medium","متوسط")},
    {id:"B",x:scan.cells.dark.x,y:scan.cells.dark.y,tone:"secondary",title:t("Possible deeper-looking zone","منطقة تبدو أعمق محتملة"),reason:t("This is one of the darker visible water areas. Darkness can have several causes, so treat depth as a possibility—not a measurement.","هذه من أغمق مناطق المياه الظاهرة. قد يكون اللون الداكن لأسباب متعددة، لذلك اعتبر العمق احتمالاً وليس قياساً."),cast:t("Start short of the zone, then cast beyond it if the retrieve lane stays clear.","ابدأ قبل المنطقة ثم ارمِ بعدها إذا ظل مسار الاسترجاع خالياً."),distance:t("Medium to long cast","رمية متوسطة إلى بعيدة"),column:t("Mid-water, then lower if clear","منتصف المياه ثم أعمق إذا كان المسار آمناً"),lure:analysisProfile.lure,retrieve:t("Steady with short pauses","ثابت مع توقفات قصيرة"),risk:risk},
    {id:"C",x:scan.cells.open.x,y:scan.cells.open.y,tone:"search",title:t("Open search lane","مسار بحث مفتوح"),reason:t("This area shows a smoother visual pattern and may offer a cleaner retrieval lane for covering water.","تظهر هذه المنطقة نمطاً أكثر هدوءاً وقد توفر مسار استرجاع أنظف لتغطية المياه."),cast:t("Fan-cast the area: near first, then progressively farther.","غطِّ المنطقة بمروحة رميات: ابدأ قريباً ثم زد المسافة تدريجياً."),distance:t("Short to long search casts","رميات بحث من القصيرة إلى البعيدة"),column:t("Surface to mid-water","السطح إلى منتصف المياه"),lure:analysisProfile.lure,retrieve:t("Vary speed every few casts","غيّر السرعة كل عدة رميات"),risk:t("Low–medium","منخفض–متوسط")},
    {id:"!",x:scan.cells.snag.x,y:scan.cells.snag.y,tone:"danger",title:t("Possible snag zone","منطقة تعليق محتملة"),reason:t("High visible texture/contrast may indicate rocks, reef, weed or another irregular feature near the lure path.","التفاصيل والتباين المرتفعان قد يشيران إلى صخور أو شعاب أو حشائش أو عائق قريب من مسار الطُعم."),cast:t("Avoid dragging near bottom. Work above it or route the retrieve around the feature.","تجنب السحب قرب القاع. اعمل فوقها أو غيّر مسار الاسترجاع حول العائق."),distance:t("Do not target directly first","لا تستهدفها مباشرة في البداية"),column:t("Upper water","أعلى المياه"),lure:t("Single-hook or front-assist setup","خطاف فردي أو أسيست أمامي"),retrieve:t("Faster, with reduced sink time","أسرع مع تقليل وقت الغوص"),risk:t("High","مرتفع")},
  ]);setActiveZone("A");setStage("result");}catch{setError(t("The image could not be analysed. Try another JPG, PNG or screenshot.","تعذر تحليل الصورة. جرّب صورة JPG أو PNG أو لقطة شاشة أخرى."));}finally{setScanning(false)}};
  const active=zones.find(z=>z.id===activeZone)??zones[0];
  const targetName=target==="unsure"?analysisProfile.suggestedTargets[0]?.[rtl?1:0]:(fish.find(x=>x[0]===target)?.[rtl?2:1]??t("Possible predator","مفترس محتمل"));
  const styleName=styles.find(x=>x[0]===analysisProfile.resolvedStyle)?.[rtl?2:1];
  const environment=analysisProfile.sandy?"sand":spotType==="reef"?"reef":analysisProfile.rocky?"rocks":"open";
  const query=`style=${analysisProfile.resolvedStyle}&fish=${target==="unsure"?"bluefish":target}&environment=${environment}&structure=${environment}&snag=${analysisProfile.rocky?"high":"medium"}`;
  const saveSpot=()=>{try{const previous=JSON.parse(localStorage.getItem("alexfisher-saved-spots")||"[]");const record={id:Date.now(),date:new Date().toISOString(),image:thumbnail,name:file?.name,style:analysisProfile.resolvedStyle,target,spotType,tide,wind,zones};localStorage.setItem("alexfisher-saved-spots",JSON.stringify([record,...previous].slice(0,8)));setSaved(true)}catch{setError(t("This device could not save the analysis.","تعذر حفظ التحليل على هذا الجهاز."))}};
  const restart=()=>{setStage("upload");setFile(null);setPreview("");setThumbnail("");setZones([]);setSaved(false);setError("")};

  return <main dir={rtl?"rtl":"ltr"} className={`spot-reader-page ${rtl?"font-arabic":""}`}>
    <header className="matcher-topbar"><a href="/fishing-hub" className="back-link"><ArrowLeft size={17}/>{t("Fishing Hub","مركز الصيد")}</a><a className="brand" href="/"><span className="brand-mark"><Waves size={22}/></span><span>ALEX<strong>FISHER</strong><small>READ MY SPOT</small></span></a><nav><a href="/fishing-hub">{t("Fishing Hub","مركز الصيد")}</a><a href="/learning">{t("Learning","تعلم")}</a><a href="/community">{t("Community","المجتمع")}</a></nav><button className="language-button" onClick={toggleLanguage}><Languages size={16}/>{rtl?"EN":"العربية"}</button></header>
    <section className="spot-reader-head"><p><ScanLine size={16}/>{t("VISUAL FISHING GUIDANCE","إرشاد بصري للصيد")}</p><h1>{t("Read My Fishing Spot","حلّل مكان الصيد")}</h1><span>{t("Upload a photo or map of your fishing location and learn how to approach it.","ارفع صورة أو خريطة لمكان الصيد وتعلم كيف تتعامل معه.")}</span></section>

    {stage==="upload"&&<section className="spot-upload-shell"><div className={`spot-dropzone ${preview?"has-image":""}`}>
      {preview?<><img src={preview} alt={t("Uploaded fishing spot","صورة مكان الصيد المرفوعة")}/><div className="spot-image-change"><button onClick={()=>uploadRef.current?.click()}><RefreshCw size={16}/>{t("Change image","غيّر الصورة")}</button></div></>:<><div className="upload-symbol"><UploadCloud size={34}/></div><h2>{t("Add your fishing spot","أضف مكان الصيد")}</h2><p>{t("Use a coastline, beach, breakwater, rocky shore or satellite screenshot.","استخدم صورة ساحل أو شاطئ أو حاجز أمواج أو صخور أو لقطة قمر صناعي.")}</p><div className="upload-actions"><button onClick={()=>cameraRef.current?.click()}><Camera size={18}/>{t("Take photo","التقط صورة")}</button><button onClick={()=>uploadRef.current?.click()}><ImageIcon size={18}/>{t("Upload image","ارفع صورة")}</button></div></>}
      <input ref={cameraRef} type="file" accept="image/*" capture="environment" hidden onChange={e=>handleFile(e.target.files?.[0])}/><input ref={uploadRef} type="file" accept="image/*" hidden onChange={e=>handleFile(e.target.files?.[0])}/>
    </div><div className="spot-accuracy-note"><ShieldAlert size={18}/><p><strong>{t("Guidance, not a guarantee","إرشاد وليس ضماناً")}</strong>{t("The tool reads visible patterns only. It cannot confirm fish, exact depth or hidden hazards.","الأداة تقرأ الأنماط الظاهرة فقط ولا تؤكد وجود السمك أو العمق الدقيق أو الأخطار المخفية.")}</p></div>{error&&<p className="spot-error">{error}</p>}<button className="analyse-spot-button" disabled={!file} onClick={beginContext}>{t("Continue to context","تابع لإضافة المعلومات")}<ArrowRight size={18}/></button></section>}

    {stage==="context"&&<section className="spot-context-shell"><div className="spot-context-preview"><img src={preview} alt=""/><button onClick={()=>setStage("upload")}><ArrowLeft size={15}/>{t("Image","الصورة")}</button></div><div className="spot-context-form"><div className="spot-section-title"><small>{t("OPTIONAL CONTEXT","معلومات اختيارية")}</small><h2>{t("Help me read it better","ساعدني على التحليل بدقة أكبر")}</h2><p>{t("You can leave any choice as “not sure.”","يمكنك ترك أي اختيار على «غير متأكد».")}</p></div><h3>{t("What kind of image is it?","ما نوع المكان أو الصورة؟")}</h3><ChoiceGrid items={spotTypes} value={spotType} onChange={setSpotType} rtl={rtl}/><h3>{t("Fishing style","طريقة الصيد")}</h3><ChoiceGrid items={styles} value={style} onChange={setStyle} rtl={rtl}/><h3>{t("Target fish","السمكة المستهدفة")}</h3><ChoiceGrid items={fish} value={target} onChange={setTarget} rtl={rtl}/><div className="spot-condition-pair"><div><h3>{t("Tide / water level","المد / مستوى المياه")}</h3><ChoiceGrid items={tideOptions.filter(x=>x[0]!=="live"||live)} value={tide} onChange={setTide} rtl={rtl}/></div><div><h3>{t("Wind","الرياح")}</h3><ChoiceGrid items={windOptions.filter(x=>x[0]!=="live"||live)} value={wind} onChange={setWind} rtl={rtl}/></div></div>{live&&<div className="live-context"><i/><div><strong>{t("Latest selected live conditions","آخر ظروف مباشرة محددة")}</strong><span>{live.city} · {live.spot} · {live.wind.toFixed(0)} km/h · {live.tideState}</span></div></div>}{error&&<p className="spot-error">{error}</p>}<button className="analyse-spot-button" onClick={analyse} disabled={scanning}>{scanning?<><RefreshCw className="spin" size={18}/>{t("Reading visible patterns…","جارٍ قراءة الأنماط الظاهرة…")}</>:<><ScanLine size={18}/>{t("Analyse My Spot","حلّل مكان الصيد")}</>}</button></div></section>}

    {stage==="result"&&active&&<><section className="spot-result-top"><div><small>{t("SPOT ANALYSIS","تحليل المكان")}</small><h2>{t("Start Here","ابدأ من هنا")}</h2><p>{t(`Cast toward Zone A, start with ${analysisProfile.lure}, work the upper-middle water column and retrieve across the visible edge.`,`ارمِ نحو المنطقة A، وابدأ بـ ${analysisProfile.lure}، واعمل في أعلى ومنتصف المياه عبر الحافة الظاهرة.`)}</p></div><div className="spot-result-actions"><button onClick={saveSpot}><Save size={16}/>{saved?t("Saved on this device","تم الحفظ على الجهاز"):t("Save this analysis","احفظ هذا التحليل")}</button><button onClick={restart}><RefreshCw size={16}/>{t("New spot","مكان جديد")}</button></div></section>
      <section className="spot-analysis-board"><div className="annotated-spot"><img src={preview} alt={t("Fishing spot with analysis zones","مكان الصيد مع مناطق التحليل")}/>{zones.map(zone=><button key={zone.id} className={`${zone.tone} ${activeZone===zone.id?"active":""}`} style={{left:`${zone.x}%`,top:`${zone.y}%`}} onClick={()=>setActiveZone(zone.id)} aria-label={zone.title}>{zone.id}</button>)}<div className="spot-overlay-legend"><span><i className="a"/>A {t("First cast","الرمية الأولى")}</span><span><i className="b"/>B {t("Possible depth","عمق محتمل")}</span><span><i className="c"/>C {t("Search","بحث")}</span><span><i className="d"/>! {t("Snag","تعليق")}</span></div></div><article className={`zone-detail ${active.tone}`}><div className="zone-title"><span>{active.id}</span><div><small>{t("SELECTED ZONE","المنطقة المحددة")}</small><h3>{active.title}</h3></div></div><p>{active.reason}</p><dl><div><dt>{t("Where to cast","أين ترمي؟")}</dt><dd>{active.cast}</dd></div><div><dt>{t("Cast range","مدى الرمية")}</dt><dd>{active.distance}</dd></div><div><dt>{t("Water column","طبقة المياه")}</dt><dd>{active.column}</dd></div><div><dt>{t("Suggested lure","الطُعم المقترح")}</dt><dd>{active.lure}</dd></div><div><dt>{t("Retrieve","الاسترجاع")}</dt><dd>{active.retrieve}</dd></div><div><dt>{t("Snag risk","خطر التعليق")}</dt><dd>{active.risk}</dd></div></dl></article></section>

      <section className="spot-summary-grid"><article className="best-style-card"><p>{t("BEST FISHING STYLE","أفضل طريقة صيد")}</p><h3>🥇 {styleName}</h3><ol><li>🥈 {analysisProfile.resolvedStyle==="casting"?t("Shore Jigging","شور جيجنج"):t("Casting / Spinning","كاستنج / سبيننج")}</li><li>🥉 {analysisProfile.sandy?t("Casting / Spinning","كاستنج / سبيننج"):t("Popping","بوبنج")}</li></ol><span>{analysisProfile.rocky?t("Visible hard structure and open lanes make controlled lure fishing practical, but sink time must be managed.","البنية الصلبة والمسارات المفتوحة تجعل صيد الطُعم المتحكم به مناسباً، مع ضرورة ضبط وقت الغوص."):t("The visible open-water pattern supports systematic fan casting before committing to maximum distance.","نمط المياه المفتوحة الظاهر يناسب الرمي المنظم على شكل مروحة قبل استخدام أقصى مسافة.")}</span></article><article className="possible-targets-card"><p>{t("POSSIBLE TARGETS","أهداف محتملة")}</p><h3>{target==="unsure"?t("Species worth considering","أنواع تستحق التجربة"):targetName}</h3><ol>{analysisProfile.suggestedTargets.map((name,index)=><li key={name[0]}><b>{index+1}</b>{name[rtl?1:0]}</li>)}</ol><span>{t("Species commonly worth targeting in this type of environment—not proof they are present now.","أنواع شائعة تستحق الاستهداف في هذا النوع من البيئة، وليس دليلاً على وجودها الآن.")}</span></article><article className="snag-risk-card"><p>{t("SNAG RISK","خطر التعليق")}</p><h3>{analysisProfile.rocky?`🔴 ${t("High","مرتفع")}`:`🟡 ${t("Medium","متوسط")}`}</h3><ul><li>{t("Work higher in the water column.","اعمل في طبقة مياه أعلى.")}</li><li>{t("Reduce sink time near marked structure.","قلل وقت الغوص قرب العوائق المحددة.")}</li><li>{t("Use a faster retrieve through danger zones.","استخدم استرجاعاً أسرع عبر مناطق الخطر.")}</li><li>{t("Consider front-assist-only jig configuration.","فكر في أسيست أمامي فقط للجيج.")}</li></ul></article></section>

      {(analysisProfile.rocky||analysisProfile.harshWind||analysisProfile.highWater)&&<section className="spot-safety-warning"><AlertTriangle/><div><strong>{t("Safety Warning","تحذير سلامة")}</strong><p>{t("Exposed rocks, elevated water or strong wind may make the standing area unsafe. The image cannot reveal every wave, slippery surface or changing hazard.","الصخور المكشوفة أو ارتفاع المياه أو الرياح القوية قد تجعل مكان الوقوف غير آمن. الصورة لا تكشف كل موجة أو سطح زلق أو خطر متغير.")}</p><b>{t("Always assess local conditions yourself before entering rocks, surf or exposed coastal areas.","قيّم الظروف بنفسك دائماً قبل دخول الصخور أو الأمواج أو المناطق الساحلية المكشوفة.")}</b></div></section>}

      <section className="what-seeing"><div className="spot-section-title"><small>{t("LEARN TO READ WATER","تعلّم قراءة المياه")}</small><h2>{t("What I’m Seeing","ما الذي أراه؟")}</h2><p>{t("Fish often use edges and changes. These are the visual clues the analysis prioritised.","الأسماك كثيراً ما تستخدم الحواف والتغيّرات. هذه هي العلامات البصرية التي أعطاها التحليل أولوية.")}</p></div><div className="seeing-grid">{[["Points & edges","الرؤوس والحواف","Where structure meets open water.","حيث تلتقي البنية بالمياه المفتوحة."],["Dark water","المياه الداكنة","A possible deeper zone, shadow or bottom-color change.","منطقة أعمق محتملة أو ظل أو تغير لون القاع."],["Current seams","حدود التيار","Lines where moving and calmer water may meet.","خطوط تلتقي عندها المياه المتحركة والأهدأ."],["Whitewater","المياه البيضاء","Oxygenated cover near rocks, but also a safety signal.","غطاء مائي مؤكسج قرب الصخور، لكنه أيضاً إشارة سلامة."],["Sand / rock edges","حدود الرمل والصخر","A change worth working along instead of crossing randomly.","تغير يستحق الصيد بمحاذاته بدلاً من الرمي العشوائي."],["Calm pockets","الجيوب الهادئة","Possible resting or ambush water beside faster flow.","مياه راحة أو كمين محتملة بجوار تيار أسرع."]].map(x=><article key={x[0]}><Compass/><h3>{t(x[0],x[1])}</h3><p>{t(x[2],x[3])}</p></article>)}</div></section>

      <section className="spot-no-bite"><div><small>{t("NO BITE?","لا توجد عضات؟")}</small><h2>{t("Change one variable after 10–20 casts.","غيّر عاملاً واحداً بعد 10–20 رمية.")}</h2></div><ol><li>{t("Change water column","غيّر طبقة المياه")}</li><li>{t("Change lure profile","غيّر شكل الطُعم")}</li><li>{t("Change color","غيّر اللون")}</li><li>{t("Try Zone B","جرّب المنطقة B")}</li><li>{t("Change retrieve speed","غيّر سرعة الاسترجاع")}</li></ol></section>

      <section className="spot-tool-links"><a href={`/tackle-matcher?${query}`}><Target/><div><small>{t("TACKLE MATCHER","مطابقة العدة")}</small><strong>{t("Build a setup for this spot","ابنِ عدة لهذا المكان")}</strong></div><ChevronRight/></a><a href={`/lure-selector?${query}`}><Fish/><div><small>{t("LURE & JIG SELECTOR","اختيار الطُعم والجيج")}</small><strong>{t("Choose what to throw","اختر ماذا سترمي")}</strong></div><ChevronRight/></a><a href={`/hook-matcher?${query}&lure=${analysisProfile.resolvedStyle==="shore-jig"?"jig":"minnow"}`}><Layers3/><div><small>{t("HOOK MATCHER","دليل الخطاف")}</small><strong>{t("Choose the hook setup","اختر تجهيز الخطاف")}</strong></div><ChevronRight/></a></section>
    </>}
  </main>;
}
