"use client";

import { useEffect, useMemo, useState } from "react";
import { AlertTriangle, ArrowLeft, ArrowRight, Check, ChevronRight, Fish, HelpCircle, Languages, Link2, Scale, Shield, Sparkles, Waves } from "lucide-react";
import BottomNav from "@/components/BottomNav";

type Language = "en" | "ar";
type Copy = { en: string; ar: string };
type Hook = {
  id: string;
  name: Copy;
  image: string;
  shape: Copy;
  best: Copy;
  avoid: Copy;
  presentation: Copy;
  set: Copy;
  snag: Copy;
  damage: Copy;
  mistake: Copy;
  strength: Copy;
};

const hooks: Hook[] = [
  { id:"j", name:{en:"J-Hook",ar:"خطاف J"}, image:"/assets/hooks/j-hook.webp", shape:{en:"Classic J profile with an open point.",ar:"شكل J تقليدي وسن مفتوح."}, best:{en:"Bait fishing, surf fishing and active hook setting.",ar:"الصيد بالطُعم والصيد من الشاطئ والضرب النشط."}, avoid:{en:"Passive bites when reducing deep hooking is the priority.",ar:"العضات السلبية عندما يكون تقليل البلع العميق أولوية."}, presentation:{en:"Shrimp, worms, strips and cut bait.",ar:"جمبري وديدان وشرائح وطُعم مقطع."}, set:{en:"Strike and set the hook firmly.",ar:"اضرب وثبّت الخطاف بقوة مناسبة."}, snag:{en:"Medium",ar:"متوسط"}, damage:{en:"Medium",ar:"متوسط"}, mistake:{en:"Burying the point or using a hook larger than the bait.",ar:"دفن السن أو استخدام خطاف أكبر من الطُعم."}, strength:{en:"Fine to heavy",ar:"رفيع إلى ثقيل"} },
  { id:"circle", name:{en:"Circle Hook",ar:"الخطاف الدائري"}, image:"/assets/hooks/circle-hook.webp", shape:{en:"Point curves inward toward the shank.",ar:"السن منحني للداخل باتجاه الساق."}, best:{en:"Natural, live or dead bait; reducing deep hooking.",ar:"الطُعم الطبيعي الحي أو الميت وتقليل البلع العميق."}, avoid:{en:"Techniques that require an aggressive instant strike.",ar:"الأساليب التي تتطلب ضربة فورية وعنيفة."}, presentation:{en:"Whole baitfish, chunks and larger natural bait.",ar:"سمكة طُعم كاملة أو قطع وطُعم طبيعي كبير."}, set:{en:"Let the line load, then increase pressure gradually. Do not strike hard.",ar:"اترك الخيط يشد ثم زِد الضغط تدريجياً. لا تضرب بعنف."}, snag:{en:"Low–medium",ar:"منخفض–متوسط"}, damage:{en:"Lower",ar:"أقل"}, mistake:{en:"Striking it like a J-hook.",ar:"ضربه مثل خطاف J."}, strength:{en:"Medium to heavy",ar:"متوسط إلى ثقيل"} },
  { id:"octopus", name:{en:"Octopus Hook",ar:"خطاف أوكتوبس"}, image:"/assets/hooks/octopus-hook.webp", shape:{en:"Short shank, compact body and wide gap.",ar:"ساق قصيرة وجسم مدمج وفتحة واسعة."}, best:{en:"Compact bait rigs and live/dead bait.",ar:"تجهيزات الطُعم المدمجة والطُعم الحي أو الميت."}, avoid:{en:"Long worms that need shank support.",ar:"الديدان الطويلة التي تحتاج ساقاً داعمة."}, presentation:{en:"Shrimp, small baitfish and cut bait.",ar:"جمبري وسمك طُعم صغير وقطع طُعم."}, set:{en:"Use a controlled positive strike.",ar:"استخدم ضربة ثابتة ومتحكم بها."}, snag:{en:"Medium",ar:"متوسط"}, damage:{en:"Medium",ar:"متوسط"}, mistake:{en:"Covering the wide gap with too much bait.",ar:"ملء الفتحة الواسعة بكمية طُعم زائدة."}, strength:{en:"Fine to medium",ar:"رفيع إلى متوسط"} },
  { id:"live", name:{en:"Live Bait Hook",ar:"خطاف الطُعم الحي"}, image:"/assets/hooks/live-bait-hook.webp", shape:{en:"Compact, strong and designed for bait movement.",ar:"مدمج وقوي ومصمم لحركة الطُعم."}, best:{en:"Live sardine, shrimp and small baitfish.",ar:"السردين الحي والجمبري وسمك الطُعم الصغير."}, avoid:{en:"Oversizing it so the live bait cannot swim.",ar:"تكبيره لدرجة تمنع الطُعم الحي من السباحة."}, presentation:{en:"Nose, back or bridle rigging as appropriate.",ar:"التعليق من الأنف أو الظهر أو الرباط حسب الحالة."}, set:{en:"Let the fish take, then set according to point style.",ar:"اترك السمكة تأخذ الطُعم ثم ثبّت حسب شكل السن."}, snag:{en:"Medium",ar:"متوسط"}, damage:{en:"Medium",ar:"متوسط"}, mistake:{en:"Using wire too heavy for the baitfish.",ar:"استخدام سلك أثقل من قدرة سمكة الطُعم."}, strength:{en:"Medium to heavy",ar:"متوسط إلى ثقيل"} },
  { id:"long", name:{en:"Long-Shank Hook",ar:"خطاف طويل الساق"}, image:"/assets/hooks/long-shank-hook.webp", shape:{en:"Extended shank between the eye and bend.",ar:"ساق طويلة بين العين والانحناء."}, best:{en:"Worms, long bait and easier hook removal.",ar:"الديدان والطُعم الطويل وسهولة نزع الخطاف."}, avoid:{en:"When a compact natural presentation is needed.",ar:"عندما تحتاج عرضاً طبيعياً مدمجاً."}, presentation:{en:"Threaded worms and long strips.",ar:"ديدان وشرائح طويلة مثبتة على الساق."}, set:{en:"Use a direct controlled strike.",ar:"استخدم ضربة مباشرة ومتحكم بها."}, snag:{en:"Medium",ar:"متوسط"}, damage:{en:"Medium",ar:"متوسط"}, mistake:{en:"Assuming the long shank replaces a bite-proof trace.",ar:"اعتبار الساق الطويلة بديلاً لليدر المقاوم للأسنان."}, strength:{en:"Fine to medium",ar:"رفيع إلى متوسط"} },
  { id:"ewg", name:{en:"Wide Gap / EWG",ar:"خطاف واسع الفتحة EWG"}, image:"/assets/hooks/wide-gap-hook.webp", shape:{en:"Extra-wide gap for bulky soft bait.",ar:"فتحة شديدة الاتساع للطُعم السميك."}, best:{en:"Soft plastics and weedless-style rigging.",ar:"الطعوم السيليكون والتركيب المقاوم للتعليق."}, avoid:{en:"Very small, thin natural bait.",ar:"الطُعم الطبيعي الصغير والرفيع جداً."}, presentation:{en:"Paddletails, creatures and bulky soft plastics.",ar:"طعوم سيليكون عريضة وذات ذيل متحرك."}, set:{en:"Reel down, then make a firm sweep-set.",ar:"لمّ الخيط ثم اسحب بثبات لتثبيت الخطاف."}, snag:{en:"Low",ar:"منخفض"}, damage:{en:"Lower",ar:"أقل"}, mistake:{en:"Choosing too little gap for the plastic thickness.",ar:"اختيار فتحة أصغر من سمك الطُعم السيليكون."}, strength:{en:"Medium to heavy",ar:"متوسط إلى ثقيل"} },
  { id:"kahle", name:{en:"Kahle Hook",ar:"خطاف كالي"}, image:"/assets/hooks/kahle-hook.webp", shape:{en:"Very wide, rounded bend and open gap.",ar:"انحناء دائري عريض وفتحة مفتوحة."}, best:{en:"Larger bait, chunk bait and live bait.",ar:"الطُعم الكبير والقطع والطُعم الحي."}, avoid:{en:"Tiny bait or highly snaggy structure.",ar:"الطُعم الصغير جداً أو الأماكن كثيرة التعليق."}, presentation:{en:"Chunks, crab and live baitfish.",ar:"قطع الطُعم والكابوريا وسمك الطُعم الحي."}, set:{en:"Use a smooth sweep rather than a violent jerk.",ar:"استخدم سحبة سلسة بدلاً من ضربة عنيفة."}, snag:{en:"Medium–high",ar:"متوسط–مرتفع"}, damage:{en:"Medium",ar:"متوسط"}, mistake:{en:"Leaving insufficient exposed gap.",ar:"عدم ترك فتحة كافية مكشوفة."}, strength:{en:"Medium to heavy",ar:"متوسط إلى ثقيل"} },
  { id:"treble", name:{en:"Treble Hook",ar:"الخطاف الثلاثي"}, image:"/assets/hooks/treble-hook.webp", shape:{en:"Three points around one central shank.",ar:"ثلاثة أسنان حول ساق مركزية."}, best:{en:"Minnows, poppers, stickbaits and hard lures.",ar:"المينو والبوبر والستيك بيت والطعوم الصلبة."}, avoid:{en:"Rocks, reef, heavy structure and careful release.",ar:"الصخور والشعاب والعوائق والصيد للإطلاق."}, presentation:{en:"Belly or tail hanger on hard lures.",ar:"أسفل أو ذيل الطُعم الصناعي الصلب."}, set:{en:"Maintain tension and use a controlled sweep.",ar:"حافظ على الشد واستخدم سحبة متحكم بها."}, snag:{en:"High",ar:"مرتفع"}, damage:{en:"Higher",ar:"أعلى"}, mistake:{en:"Oversizing it and killing the lure action.",ar:"تكبيره بما يفسد حركة الطُعم."}, strength:{en:"Fine to heavy",ar:"رفيع إلى ثقيل"} },
  { id:"inline", name:{en:"Inline Single Hook",ar:"الخطاف الفردي المستقيم"}, image:"/assets/hooks/inline-single-hook.webp", shape:{en:"Single lure hook with the eye aligned to the point.",ar:"خطاف فردي للطُعم وعينه بمحاذاة السن."}, best:{en:"Replacing trebles, reducing snags and fish damage.",ar:"استبدال الثلاثي وتقليل التعليق وضرر السمكة."}, avoid:{en:"Incorrect orientation or weight that unbalances the lure.",ar:"الاتجاه الخاطئ أو وزن يخل بتوازن الطُعم."}, presentation:{en:"Minnow, popper and stickbait replacement.",ar:"بديل على المينو والبوبر والستيك بيت."}, set:{en:"Keep pressure and sweep firmly.",ar:"حافظ على الضغط واسحب بثبات."}, snag:{en:"Low–medium",ar:"منخفض–متوسط"}, damage:{en:"Lower",ar:"أقل"}, mistake:{en:"Mounting the point in the wrong orientation.",ar:"تركيب السن في الاتجاه الخطأ."}, strength:{en:"Medium to heavy",ar:"متوسط إلى ثقيل"} },
  { id:"assist", name:{en:"Assist Hook",ar:"خطاف الأسيست"}, image:"/assets/hooks/assist-hook.webp", shape:{en:"Short cord connects a single or twin hook to the jig eye.",ar:"حبل قصير يصل خطافاً فردياً أو مزدوجاً بعين الجيج."}, best:{en:"Shore jigging and boat jigging.",ar:"الشور جيجنج والبوت جيجنج."}, avoid:{en:"A long rear assist where it tangles or snags repeatedly.",ar:"الأسيست الخلفي الطويل عندما يتشابك أو يعلق."}, presentation:{en:"Front single/twin; rear only when conditions suit.",ar:"فردي أو مزدوج أمامي؛ والخلفي عند ملاءمة الظروف."}, set:{en:"Maintain tension through the strike and retrieve.",ar:"حافظ على شد الخيط أثناء الضربة والاسترجاع."}, snag:{en:"Low–medium",ar:"منخفض–متوسط"}, damage:{en:"Lower",ar:"أقل"}, mistake:{en:"Using a cord so long that the hook reaches the jig body excessively.",ar:"استخدام حبل طويل يجعل الخطاف يتجاوز جسم الجيج كثيراً."}, strength:{en:"Medium-heavy to heavy duty",ar:"متوسط ثقيل إلى شديد التحمل"} },
  { id:"jighead", name:{en:"Jig Head Hook",ar:"خطاف الجيج هيد"}, image:"/assets/hooks/jig-head-hook.webp", shape:{en:"Weighted head moulded onto a single hook.",ar:"رأس رصاص مثبت على خطاف فردي."}, best:{en:"Soft plastics, casting and bottom control.",ar:"السيليكون والكاستنج والتحكم قرب القاع."}, avoid:{en:"A head too heavy for depth, current or lure action.",ar:"رأس أثقل من العمق أو التيار أو حركة الطُعم."}, presentation:{en:"Paddletails, worms and soft shads.",ar:"بادل تيل وديدان وسيليكون شاد."}, set:{en:"Feel the bite, reel down and strike firmly.",ar:"اشعر بالعضة ولم الخيط ثم اضرب بثبات."}, snag:{en:"Medium–high",ar:"متوسط–مرتفع"}, damage:{en:"Medium",ar:"متوسط"}, mistake:{en:"Rigging the plastic crooked or hiding the point.",ar:"تركيب السيليكون معوجاً أو إخفاء السن."}, strength:{en:"Fine to heavy",ar:"رفيع إلى ثقيل"} },
  { id:"tuna", name:{en:"Heavy-Duty / Tuna Hook",ar:"خطاف التونة شديد التحمل"}, image:"/assets/hooks/tuna-hook.webp", shape:{en:"Compact heavy wire built for extreme load.",ar:"سلك ثقيل مدمج لتحمل أحمال كبيرة."}, best:{en:"Tuna, GT, amberjack and large pelagic fish.",ar:"التونة والجي تي والأمبرجاك والأسماك السطحية الكبيرة."}, avoid:{en:"Small bait or light tackle that cannot drive thick wire.",ar:"الطُعم الصغير أو العدة الخفيفة التي لا تثبت السلك السميك."}, presentation:{en:"Large bait, trolling and heavy live-bait rigs.",ar:"طُعم كبير وجر وتجهيزات طُعم حي ثقيلة."}, set:{en:"Build heavy pressure with a loaded rod and tight drag system.",ar:"ابنِ ضغطاً قوياً بقصبة محملة وفرامل مضبوطة."}, snag:{en:"Medium",ar:"متوسط"}, damage:{en:"Medium",ar:"متوسط"}, mistake:{en:"Using heavy wire without enough tackle power to penetrate.",ar:"استخدام سلك ثقيل دون قوة عدة كافية للاختراق."}, strength:{en:"3X, 4X or heavy duty",ar:"3X أو 4X أو شديد التحمل"} },
  { id:"grouper", name:{en:"Grouper / Reef Hook",ar:"خطاف الهامور والشعاب"}, image:"/assets/hooks/grouper-hook.webp", shape:{en:"Short, very strong heavy-wire profile.",ar:"شكل قصير شديد القوة بسلك ثقيل."}, best:{en:"Grouper, reef fishing and heavy structure.",ar:"الهامور والصيد على الشعاب والعوائق الثقيلة."}, avoid:{en:"Small delicate bait or light line.",ar:"الطُعم الدقيق أو الخيط الخفيف."}, presentation:{en:"Large live bait and chunk bait.",ar:"طُعم حي كبير وقطع طُعم."}, set:{en:"Apply pressure immediately and turn the fish away from cover.",ar:"اضغط فوراً ووجّه السمكة بعيداً عن العوائق."}, snag:{en:"Medium–high",ar:"متوسط–مرتفع"}, damage:{en:"Medium",ar:"متوسط"}, mistake:{en:"Pairing a strong hook with leader too weak for structure.",ar:"تركيب خطاف قوي مع ليدر أضعف من العوائق."}, strength:{en:"4X / heavy duty",ar:"4X / شديد التحمل"} },
  { id:"baitholder", name:{en:"Baitholder Hook",ar:"خطاف حامل الطُعم"}, image:"/assets/hooks/baitholder-hook.webp", shape:{en:"Long Aberdeen-style shank with small barbs cut into the back to grip bait.",ar:"ساق طويلة على طراز أبردين مع نتوءات صغيرة خلفية لتثبيت الطُعم."}, best:{en:"Shore and surf fishing with worms, strips or cut bait that would otherwise slide down the shank.",ar:"الصيد من الشاطئ بالديدان والشرائح وقطع الطُعم التي قد تنزلق على الساق."}, avoid:{en:"Delicate live bait, since the barbs can tear it.",ar:"الطُعم الحي الرقيق لأن النتوءات قد تمزقه."}, presentation:{en:"Worms, sardine strips, squid strips and small cut bait.",ar:"الديدان وشرائح السردين والسبيط وقطع الطُعم الصغيرة."}, set:{en:"Strike and set the hook firmly, like a standard J-hook.",ar:"اضرب وثبّت الخطاف بقوة مثل خطاف J العادي."}, snag:{en:"Medium",ar:"متوسط"}, damage:{en:"Medium",ar:"متوسط"}, mistake:{en:"Threading bait past the barbs so it no longer stays gripped.",ar:"تمرير الطُعم متجاوزاً النتوءات فلا يبقى مثبتاً."}, strength:{en:"Fine to medium",ar:"رفيع إلى متوسط"} },
];

const styles = [
  ["surf","Surf Fishing","صيد الشاطئ"], ["casting","Casting / Spinning","كاستنج / سبيننج"], ["shore-jig","Shore Jigging","شور جيجنج"],
  ["boat-jig","Boat Jigging","بوت جيجنج"], ["popping","Popping","بوبنج"], ["bait","Bait Fishing","الصيد بالطُعم"],
];
const fish = [
  ["bluefish","Bluefish","مياس"], ["barracuda","Barracuda","باراكودا"], ["needlefish","Needlefish","خرمان"], ["seabass","Sea Bass","قاروص"],
  ["seabream","Sea Bream","دنيس"], ["mormora","Mormora","مرمار"], ["bonito","Bonito","بلاميطة"], ["mackerel","Mackerel","ماكريل"],
  ["leerfish","Leerfish","لوت"], ["grouper","Grouper","هامور"], ["amberjack","Amberjack","أمبرجاك"], ["mahi","Mahi Mahi","ماهي ماهي"],
  ["gt","GT","جي تي"], ["queenfish","Queenfish","كوين فيش"], ["tuna","Tuna","تونة"], ["snapper","Snapper","نهاش"],
];
const sizes = [["u1","Under 1 kg","أقل من 1 كجم"],["1-3","1–3 kg","1–3 كجم"],["3-5","3–5 kg","3–5 كجم"],["5-10","5–10 kg","5–10 كجم"],["10-20","10–20 kg","10–20 كجم"],["20-40","20–40 kg","20–40 كجم"],["40+","40 kg+","40 كجم+"]];
const natural = [["shrimp","Shrimp","جمبري"],["worm","Worm","دود"],["strip","Sardine strip","شريحة سردين"],["sardine","Whole sardine","سردينة كاملة"],["live","Live baitfish","سمكة طُعم حية"],["dead","Dead baitfish","سمكة طُعم ميتة"],["squid","Squid","سبيط"],["crab","Crab","كابوريا"],["chunk","Chunk bait","قطعة طُعم"]];
const artificial = [["jig","Metal jig","جيج معدني"],["minnow","Minnow","مينو"],["popper","Popper","بوبر"],["stickbait","Stickbait","ستيك بيت"],["soft","Soft plastic","طُعم سيليكون"],["pencil","Sinking pencil","سنكنج بنسل"]];
const structures = [["sand","Sand","رمل"],["mixed","Mixed sand / rock","رمل وصخور"],["rocks","Rocks","صخور"],["reef","Reef","شعاب"],["harbour","Harbour","ميناء"],["open","Open water","مياه مفتوحة"],["heavy","Heavy structure","عوائق كثيفة"]];

function OptionGrid({items,value,onChange,rtl}:{items:string[][];value:string;onChange:(v:string)=>void;rtl:boolean}) {
  return <div className="hook-options">{items.map(([id,en,ar])=><button type="button" key={id} className={value===id?"selected":""} onClick={()=>onChange(id)}>{rtl?ar:en}{value===id&&<Check size={15}/>}</button>)}</div>;
}

export default function HookMatcherPage(){
  const [language,setLanguage]=useState<Language>("en");
  const [step,setStep]=useState(1);
  const [style,setStyle]=useState("shore-jig");
  const [target,setTarget]=useState("bluefish");
  const [customFishName,setCustomFishName]=useState("");
  const [customToothy,setCustomToothy]=useState(false);
  const [size,setSize]=useState("3-5");
  const [source,setSource]=useState<"natural"|"artificial">("artificial");
  const [item,setItem]=useState("jig");
  const [structure,setStructure]=useState("rocks");
  const [condition,setCondition]=useState("normal");
  const [activeHook,setActiveHook]=useState("circle");
  const [anatomy,setAnatomy]=useState("gap");
  const [compareA,setCompareA]=useState("circle");
  const [compareB,setCompareB]=useState("j");
  const rtl=language==="ar";
  const t=(en:string,ar:string)=>rtl?ar:en;

  useEffect(()=>{ const saved=window.localStorage.getItem("alexfisher-language"); if(saved==="ar"||saved==="en")setLanguage(saved); const params=new URLSearchParams(window.location.search); const nextStyle=params.get("style"),nextFish=params.get("fish"),nextStructure=params.get("structure"),nextLure=params.get("lure"); if(nextStyle&&styles.some(option=>option[0]===nextStyle))setStyle(nextStyle); if(nextFish&&fish.some(option=>option[0]===nextFish))setTarget(nextFish); if(nextStructure&&structures.some(option=>option[0]===nextStructure))setStructure(nextStructure); if(nextLure){setSource("artificial");setItem(nextLure);} },[]);
  const toggleLanguage=()=>{const next=rtl?"en":"ar";setLanguage(next);window.localStorage.setItem("alexfisher-language",next)};
  useEffect(()=>{ setItem(current=>source==="natural"?(natural.some(option=>option[0]===current)?current:"shrimp"):(artificial.some(option=>option[0]===current)?current:"jig")); },[source]);

  const recommendation=useMemo(()=>{
    const snag=["rocks","reef","heavy"].includes(structure);
    const powerful=["grouper","amberjack","gt","tuna"].includes(target)||["20-40","40+"].includes(size);
    let id="j", alt="circle", position=t("Mainline bait hook","خطاف الطُعم الرئيسي"), why=t("A versatile bait hook that matches an active fishing technique.","خطاف طُعم عملي يناسب أسلوب الصيد النشط."), range=t("Match #4–2/0 to the bait profile","طابق #4–2/0 مع حجم الطُعم"), rating=t("Good match","اختيار جيد");
    if(powerful){id=target==="grouper"?"grouper":"tuna";alt="circle";range=t("Heavy-duty 5/0–10/0; verify actual gap dimensions","شديد التحمل 5/0–10/0؛ تحقق من أبعاد الفتحة");why=t("Powerful fish and high load require thick wire and tackle that can drive it.","السمكة القوية والحمل العالي يحتاجان سلكاً سميكاً وعدة قادرة على تثبيته.");rating=t("Excellent match","اختيار ممتاز")}
    if(source==="natural"&&["live","dead","sardine","chunk"].includes(item)){id="circle";alt="live";position=t("Mainline or bridle bait hook","خطاف رئيسي أو تركيب بالرباط");why=t("The inward point suits larger natural bait and can reduce deep hooking when pressure builds gradually.","السن الداخلي يناسب الطُعم الطبيعي الكبير وقد يقلل البلع العميق عند زيادة الضغط تدريجياً.");range=t("2/0–7/0, sized to keep the bait and hook gap exposed","2/0–7/0 مع إبقاء فتحة الخطاف مكشوفة");rating=t("Excellent match","اختيار ممتاز")}
    if(source==="natural"&&item==="worm"){id="long";alt="baitholder";why=t("The long shank supports a long bait and makes removal easier.","الساق الطويلة تدعم الطُعم الطويل وتسهل نزع الخطاف.");range=t("#8–1/0 according to worm thickness","#8–1/0 حسب سمك الدودة")}
    if(source==="natural"&&["strip","squid"].includes(item)){id="baitholder";alt="j";position=t("Mainline shore/surf bait hook","خطاف رئيسي للصيد من الشاطئ");why=t("The shank barbs grip a thin strip or squid piece so it stays put through the cast and the retrieve.","نتوءات الساق تثبت الشريحة أو قطعة السبيط الرقيقة أثناء الرمي والاسترجاع.");range=t("#4–2/0 to the strip width","#4–2/0 حسب عرض الشريحة")}
    if(source==="artificial"&&item==="soft"){id=snag?"ewg":"jighead";alt=snag?"jighead":"ewg";position=t(snag?"Weedless-style rig":"Weighted front hook","تركيب مقاوم للتعليق");why=t(snag?"A protected point lowers snag exposure around structure.":"A jig head controls depth and keeps the soft plastic working correctly.",snag?"السن المحمي يقلل التعليق حول العوائق.":"الجيج هيد يتحكم في العمق ويحافظ على حركة السيليكون.");range=t("Keep enough gap clear after rigging the plastic","اترك فتحة كافية بعد تركيب السيليكون")}
    if(source==="artificial"&&["minnow","popper","stickbait","pencil"].includes(item)){id=snag?"inline":"treble";alt=snag?"treble":"inline";position=t("Lure belly/tail replacement","بديل أسفل أو ذيل الطُعم");why=t(snag?"An inline single reduces snag points and fish damage while preserving lure balance.":"A correctly sized treble offers multiple contact points on open water.",snag?"الفردي المستقيم يقلل نقاط التعليق وضرر السمكة مع الحفاظ على توازن الطُعم.":"الخطاف الثلاثي بالحجم الصحيح يوفر نقاط تثبيت متعددة في المياه المفتوحة.");range=t("Match hook mass and gape to the original lure hardware","طابق وزن وفتحة الخطاف مع تجهيز الطُعم الأصلي")}
    if(source==="artificial"&&item==="jig"){id="assist";alt="inline";position=t(snag?"Front single or twin assist; no automatic rear treble":"Front single/twin assist; rear optional","أسيست فردي أو مزدوج أمامي؛ لا ثلاثي خلفي تلقائياً");why=t(snag?"A front assist keeps good exposure around the jig head with less bottom snagging than a large rear treble.":"An assist hook follows jig strikes without adding excessive drag.",snag?"الأسيست الأمامي يوفر كشفاً جيداً قرب رأس الجيج مع تعليق أقل من الثلاثي الخلفي الكبير.":"الأسيست يتعامل مع ضربات الجيج دون مقاومة زائدة.");range=t("Assist gap about the jig width; cord should not overreach the body","فتحة الأسيست قريبة من عرض الجيج والحبل لا يتجاوز الجسم");rating=t("Excellent match","اختيار ممتاز")}
    const hook=hooks.find(h=>h.id===id)!;
    const tooth=target==="other"?customToothy:["bluefish","barracuda","mackerel"].includes(target);
    const targetLabel=target==="other"?(customFishName.trim()||t("this species","هذه السمكة")):(rtl?fish.find(f=>f[0]===target)?.[2]:fish.find(f=>f[0]===target)?.[1])||target;
    return {hook,alternative:hooks.find(h=>h.id===alt)!,position,why,range,rating,snag,tooth,targetLabel};
  },[style,target,size,source,item,structure,condition,customFishName,customToothy,rtl]);

  const anatomyCopy:Record<string,Copy>={eye:{en:"Connects the hook to line, split ring or assist cord. Eye style affects alignment.",ar:"تربط الخطاف بالخيط أو الحلقة أو حبل الأسيست ويؤثر اتجاهها في المحاذاة."},shank:{en:"Controls bait support, leverage and the overall hook profile.",ar:"تتحكم في دعم الطُعم والرافعة والشكل العام للخطاف."},bend:{en:"The curved load-bearing section. Its shape influences strength and holding power.",ar:"الجزء المنحني الحامل للحمل ويؤثر شكله في القوة والثبات."},gap:{en:"Must remain open after bait is attached so the point can penetrate properly.",ar:"يجب أن تبقى مفتوحة بعد تركيب الطُعم حتى يخترق السن بشكل صحيح."},point:{en:"The penetrating tip; keep it sharp, exposed and free of corrosion.",ar:"سن الاختراق؛ يجب أن يبقى حاداً ومكشوفاً وخالياً من الصدأ."},barb:{en:"Helps retain the fish but increases removal difficulty and potential damage.",ar:"يساعد على تثبيت السمكة لكنه يزيد صعوبة النزع والضرر المحتمل."},throat:{en:"Distance from the point down toward the bend; affects holding depth.",ar:"المسافة من السن باتجاه الانحناء وتؤثر في عمق التثبيت."},offset:{en:"Sideways point offset can improve exposure but may change hooking behaviour.",ar:"انحراف السن جانبياً قد يزيد الكشف لكنه يغير سلوك التثبيت."}};
  const active=hooks.find(h=>h.id===activeHook)!; const left=hooks.find(h=>h.id===compareA)!; const right=hooks.find(h=>h.id===compareB)!;
  const canNext=step===1?!!style:step===2?!!target&&!!size:step===3?!!item:step===4?!!structure:true;

  return <main dir={rtl?"rtl":"ltr"} className={`hook-page ${rtl?"font-arabic":""}`}>
    <header className="matcher-topbar">
      <a href="/fishing-hub" className="back-link"><ArrowLeft size={17}/>{t("Fishing Hub","مركز الصيد")}</a>
      <a className="brand" href="/"><span className="brand-mark"><Waves size={22}/></span><span>ALEX<strong>FISHER</strong><small>HOOK MATCHER</small></span></a>
      <nav><a href="/fishing-hub">{t("Fishing Hub","مركز الصيد")}</a><a href="/learning">{t("Learning","تعلم")}</a><a href="/community">{t("Community","المجتمع")}</a></nav>
      <button className="language-button" onClick={toggleLanguage}><Languages size={16}/>{rtl?"EN":"العربية"}</button>
    </header>

    <section className="hook-hero">
      <div><p><Sparkles size={14}/>{t("STOP GUESSING AT THE TACKLE SHOP","توقف عن التخمين في محل أدوات الصيد")}</p><h1>{t("Hook Matcher","دليل اختيار الخطاف")}</h1><span>{t("Choose the hook, strength and position that fit how you actually fish—and understand why.","اختر نوع الخطاف وقوته وموضعه حسب طريقة صيدك وافهم السبب.")}</span></div>
      <img src="/assets/hooks/circle-hook.webp" alt={t("Circle fishing hook","خطاف صيد دائري")}/>
    </section>

    <section className="hook-matcher-shell">
      <div className="hook-progress">{[1,2,3,4,5].map(n=><span key={n} className={step>=n?"active":""}><b>{n}</b>{n<5&&<i/>}</span>)}</div>
      {step===1&&<div className="hook-step"><small>{t("STEP 1 OF 5","الخطوة 1 من 5")}</small><h2>{t("How are you fishing?","ما طريقة الصيد؟")}</h2><OptionGrid items={styles} value={style} onChange={setStyle} rtl={rtl}/></div>}
      {step===2&&<div className="hook-step"><small>{t("STEP 2 OF 5","الخطوة 2 من 5")}</small><h2>{t("Target fish and size","السمكة المستهدفة وحجمها")}</h2><h3>{t("Target fish","السمكة المستهدفة")}</h3><div className="hook-options">{fish.map(([id,en,ar])=><button type="button" key={id} className={target===id?"selected":""} onClick={()=>setTarget(id)}>{rtl?ar:en}{target===id&&<Check size={15}/>}</button>)}<button type="button" className={target==="other"?"selected":""} onClick={()=>setTarget("other")}>{t("Other / not listed","أخرى / غير مدرجة")}{target==="other"&&<Check size={15}/>}</button></div>{target==="other"&&<div className="hook-custom-fish"><label>{t("Fish name (optional)","اسم السمكة (اختياري)")}<input type="text" value={customFishName} onChange={(e)=>setCustomFishName(e.target.value)} placeholder={t("e.g. Hamour","مثال: هامور")}/></label><button type="button" className={customToothy?"selected":""} onClick={()=>setCustomToothy(v=>!v)}>{customToothy&&<Check size={15}/>}{t("Has sharp teeth or can bite through leader","لديها أسنان حادة قد تقطع الليدر")}</button></div>}<h3>{t("Expected weight","الوزن المتوقع")}</h3><OptionGrid items={sizes} value={size} onChange={setSize} rtl={rtl}/></div>}
      {step===3&&<div className="hook-step"><small>{t("STEP 3 OF 5","الخطوة 3 من 5")}</small><h2>{t("What are you using?","ماذا ستستخدم؟")}</h2><div className="hook-source"><button className={source==="natural"?"selected":""} onClick={()=>setSource("natural")}>{t("Natural bait","طُعم طبيعي")}</button><button className={source==="artificial"?"selected":""} onClick={()=>setSource("artificial")}>{t("Artificial lure","طُعم صناعي")}</button></div><OptionGrid items={source==="natural"?natural:artificial} value={item} onChange={setItem} rtl={rtl}/></div>}
      {step===4&&<div className="hook-step"><small>{t("STEP 4 OF 5","الخطوة 4 من 5")}</small><h2>{t("Structure and conditions","القاع والظروف")}</h2><h3>{t("Where are you fishing?","أين تصيد؟")}</h3><OptionGrid items={structures} value={structure} onChange={setStructure} rtl={rtl}/><h3>{t("Fishing conditions","ظروف الصيد")}</h3><OptionGrid items={[["calm","Calm","هادئة"],["normal","Normal","عادية"],["rough","Rough / strong current","أمواج أو تيار قوي"]]} value={condition} onChange={setCondition} rtl={rtl}/></div>}
      {step===5&&<div className="hook-result">
        <div className="hook-result-main"><div className="match-pill"><Check size={15}/>{recommendation.rating}</div><p>{t("RECOMMENDED HOOK SETUP","تجهيز الخطاف المقترح")}</p><h2>{rtl?recommendation.hook.name.ar:recommendation.hook.name.en}</h2><span className="hook-result-for">{t("For","لـ")} {recommendation.targetLabel} · {sizes.find(s=>s[0]===size)?.[rtl?2:1]}</span><img src={recommendation.hook.image} alt={rtl?recommendation.hook.name.ar:recommendation.hook.name.en}/></div>
        <div className="hook-result-details"><div><small>{t("POSITION","الموضع")}</small><strong>{recommendation.position}</strong></div><div><small>{t("SIZE GUIDE","دليل الحجم")}</small><strong>{recommendation.range}</strong></div><div><small>{t("WIRE STRENGTH","قوة السلك")}</small><strong>{rtl?recommendation.hook.strength.ar:recommendation.hook.strength.en}</strong></div><div><small>{t("HOOK-SET","طريقة التثبيت")}</small><strong>{rtl?recommendation.hook.set.ar:recommendation.hook.set.en}</strong></div><article><h3>{t("Why this works","لماذا يناسبك؟")}</h3><p>{recommendation.why}</p></article><article><h3>{t("Common mistake","خطأ شائع")}</h3><p>{rtl?recommendation.hook.mistake.ar:recommendation.hook.mistake.en}</p></article><article><h3>{t("Alternative","البديل")}</h3><p>{rtl?recommendation.alternative.name.ar:recommendation.alternative.name.en}</p></article></div>
        {recommendation.snag&&<div className="hook-warning"><AlertTriangle/><div><strong>{t("Snag warning","تحذير من التعليق")}</strong><p>{t("Rocky structure increases snag risk. Avoid an exposed rear treble unless there is a clear reason to use it.","الصخور ترفع خطر التعليق. تجنب الثلاثي الخلفي المكشوف إلا عند وجود سبب واضح لاستخدامه.")}</p></div></div>}
        {recommendation.tooth&&<div className="hook-warning tooth"><Shield/><div><strong>{t("Tooth risk","خطر الأسنان")}</strong><p>{t("Hook strength does not prevent bite-offs. Use an appropriate abrasion-resistant or wire trace and verify it in Tackle Matcher.","قوة الخطاف لا تمنع قطع الخيط. استخدم ليدر مقاوماً للاحتكاك أو سلكاً مناسباً وراجعه في مطابقة العدة.")}</p><a href="/tackle-matcher">{t("Open Tackle Matcher","افتح مطابقة العدة")}<ChevronRight size={15}/></a></div></div>}
        <div className="hook-result-actions"><a href="/tackle-matcher"><Link2/>{t("Match the complete tackle","طابق العدة كاملة")}</a><a href="/lure-selector"><Fish/>{t("Choose the lure or jig","اختر الطُعم أو الجيج")}</a></div>
      </div>}
      <div className="hook-step-actions">{step>1&&<button onClick={()=>setStep(s=>s-1)}><ArrowLeft size={17}/>{t("Back","السابق")}</button>}{step<5?<button className="primary" disabled={!canNext} onClick={()=>setStep(s=>s+1)}>{t("Continue","التالي")}<ArrowRight size={17}/></button>:<button className="primary" onClick={()=>setStep(1)}>{t("Start again","ابدأ من جديد")}</button>}</div>
    </section>

    <section className="hook-learning">
      <div className="hook-section-head"><p>{t("VISUAL HOOK LIBRARY","مكتبة الخطافات المصورة")}</p><h2>{t("Learn Hooks","تعلم الخطافات")}</h2><span>{t("Tap a hook to understand its shape, purpose and correct technique.","اضغط على أي خطاف لتفهم شكله واستخدامه وطريقة التعامل معه.")}</span></div>
      <div className="hook-library-grid">{hooks.map(h=><button key={h.id} className={activeHook===h.id?"active":""} onClick={()=>setActiveHook(h.id)}><img src={h.image} alt={rtl?h.name.ar:h.name.en}/><strong>{rtl?h.name.ar:h.name.en}</strong><span>{rtl?h.shape.ar:h.shape.en}</span></button>)}</div>
      <div className="hook-library-detail"><img src={active.image} alt={rtl?active.name.ar:active.name.en}/><div><p>{t("HOOK PROFILE","ملف الخطاف")}</p><h3>{rtl?active.name.ar:active.name.en}</h3><div className="hook-detail-grid"><article><small>{t("KEY SHAPE","الشكل")}</small><span>{rtl?active.shape.ar:active.shape.en}</span></article><article><small>{t("BEST FOR","الأنسب")}</small><span>{rtl?active.best.ar:active.best.en}</span></article><article><small>{t("AVOID WHEN","تجنبه عندما")}</small><span>{rtl?active.avoid.ar:active.avoid.en}</span></article><article><small>{t("BAIT / LURE","الطُعم")}</small><span>{rtl?active.presentation.ar:active.presentation.en}</span></article><article><small>{t("HOOK-SET","طريقة التثبيت")}</small><span>{rtl?active.set.ar:active.set.en}</span></article><article><small>{t("RISK","المخاطر")}</small><span>{t("Snag","تعليق")}: {rtl?active.snag.ar:active.snag.en} · {t("Fish damage","ضرر السمكة")}: {rtl?active.damage.ar:active.damage.en}</span></article></div></div></div>
    </section>

    <section className="hook-education-grid">
      <article className="hook-anatomy"><div><p>{t("HOOK ANATOMY","تشريح الخطاف")}</p><h2>{t("Every part has a job","كل جزء له وظيفة")}</h2><img src="/assets/hooks/j-hook.webp" alt={t("J-hook anatomy reference","مرجع تشريح خطاف J")}/></div><div><div className="anatomy-buttons">{Object.keys(anatomyCopy).map(key=><button key={key} className={anatomy===key?"active":""} onClick={()=>setAnatomy(key)}>{t(key[0].toUpperCase()+key.slice(1),({eye:"العين",shank:"الساق",bend:"الانحناء",gap:"الفتحة",point:"السن",barb:"اللسان",throat:"الحلق",offset:"الانحراف"} as Record<string,string>)[key])}</button>)}</div><div className="anatomy-answer"><HelpCircle/><p>{rtl?anatomyCopy[anatomy].ar:anatomyCopy[anatomy].en}</p></div></div></article>
      <article className="hook-size-guide"><p>{t("HOOK SIZE GUIDE","دليل أحجام الخطاف")}</p><h2>{t("The numbering changes at /0","يتغير نظام الترقيم عند ‎/0")}</h2><div className="size-flow"><span>#12</span><span>#8</span><span>#4</span><span>#1</span><b>1/0</b><b>3/0</b><b>5/0</b></div><div className="size-scale"><small>{t("SMALLER","أصغر")}</small><i/><small>{t("LARGER","أكبر")}</small></div><p>{t("Before /0, a lower number means a larger hook. After 1/0, a higher number means a larger hook.","قبل ‎/0 يعني الرقم الأقل خطافاً أكبر. بعد 1/0 يعني الرقم الأعلى خطافاً أكبر.")}</p><div className="hook-note"><AlertTriangle size={17}/>{t("Hook labels are not perfectly standardized between manufacturers. Compare gap, shank length, overall length and wire diameter when available.","مقاسات الخطافات ليست موحدة تماماً بين الشركات. قارن الفتحة وطول الساق والطول الكلي وقطر السلك عند توفرها.")}</div></article>
    </section>

    <section className="wire-section"><div className="hook-section-head"><p>{t("WIRE STRENGTH","قوة سلك الخطاف")}</p><h2>{t("Strong enough—but still able to penetrate","قوي بما يكفي وقابل للاختراق")}</h2></div><div className="wire-grid">{[
      ["Fine wire","سلك رفيع","Easy penetration and natural bait action.","اختراق أسهل وحركة طبيعية للطُعم.","Lower strength.","قوة أقل."],
      ["Medium wire","سلك متوسط","Balanced, general-purpose choice.","اختيار متوازن وعام.","Not ideal for extreme loads.","غير مناسب للأحمال الشديدة."],
      ["Heavy wire","سلك ثقيل","High strength for powerful fish.","قوة عالية للأسماك القوية.","Needs more force and may affect bait action.","يحتاج قوة أكبر وقد يؤثر في حركة الطُعم."],
    ].map((x,i)=><article key={x[0]}><Scale/><small>{["STANDARD / FINE","2X–3X / MEDIUM","3X–4X / HEAVY DUTY"][i]}</small><h3>{t(x[0],x[1])}</h3><p className="pro">+ {t(x[2],x[3])}</p><p className="con">− {t(x[4],x[5])}</p></article>)}</div></section>

    <section className="hook-compare"><div className="hook-section-head"><p>{t("SIDE-BY-SIDE","مقارنة مباشرة")}</p><h2>{t("Compare Hooks","قارن الخطافات")}</h2></div><div className="compare-selects"><select value={compareA} onChange={e=>setCompareA(e.target.value)}>{hooks.map(h=><option key={h.id} value={h.id}>{rtl?h.name.ar:h.name.en}</option>)}</select><b>VS</b><select value={compareB} onChange={e=>setCompareB(e.target.value)}>{hooks.map(h=><option key={h.id} value={h.id}>{rtl?h.name.ar:h.name.en}</option>)}</select></div><div className="compare-table"><div/><strong>{rtl?left.name.ar:left.name.en}</strong><strong>{rtl?right.name.ar:right.name.en}</strong>{[["Hook-set","طريقة التثبيت","set"],["Best for","الأنسب","best"],["Strength","القوة","strength"],["Snag risk","خطر التعليق","snag"],["Fish damage","ضرر السمكة","damage"]].map(([en,ar,key])=><div className="compare-row" key={key}><b>{t(en,ar)}</b><span>{rtl?(left as any)[key].ar:(left as any)[key].en}</span><span>{rtl?(right as any)[key].ar:(right as any)[key].en}</span></div>)}</div></section>

    <section className="hook-future"><div><small>{t("COMING LATER","قريباً")}</small><h2>{t("What Hook Is This?","ما نوع هذا الخطاف؟")}</h2><p>{t("Upload a photo to estimate the hook family and visible features. Exact brand or model identification will only be shown when reliable.","ارفع صورة لتقدير عائلة الخطاف وخصائصه الظاهرة. لن نحدد الماركة أو الموديل إلا عند موثوقية النتيجة.")}</p></div><div className="future-icon">?</div></section>
    <BottomNav active="fishing-hub" />
  </main>;
}
