create or replace function public.is_admin()
returns boolean language sql stable security definer set search_path=public
as $$ select exists(select 1 from public.profiles where id=auth.uid() and role='admin') $$;

alter table public.profiles add column if not exists account_status text not null default 'active' check(account_status in('active','suspended'));

create table public.subscription_plans(code text primary key,name text not null,description text not null default '',duration_months integer not null default 1 check(duration_months between 0 and 120),price_amount numeric(10,2) not null default 0 check(price_amount>=0),currency text not null default 'USD',is_active boolean not null default false,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.member_subscriptions(id uuid primary key default gen_random_uuid(),user_id uuid not null references public.profiles on delete cascade,plan_code text not null references public.subscription_plans(code),status text not null default 'active' check(status in('trialing','active','past_due','cancelled','expired')),duration_months integer not null check(duration_months between 0 and 120),starts_at timestamptz not null default now(),ends_at timestamptz,auto_renew boolean not null default false,source text not null default 'admin',notes text not null default '',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create index idx_member_subscriptions_user on public.member_subscriptions(user_id,created_at desc);
create index idx_member_subscriptions_status on public.member_subscriptions(status,ends_at);
create table public.feature_catalog(feature_key text primary key,name text not null,category text not null default 'general',description text not null default '',is_active boolean not null default true,created_at timestamptz not null default now());
create table public.plan_features(plan_code text references public.subscription_plans on delete cascade,feature_key text references public.feature_catalog on delete cascade,enabled boolean not null default true,limits jsonb not null default '{}'::jsonb,primary key(plan_code,feature_key));
create table public.admin_audit_log(id bigint generated always as identity primary key,admin_id uuid references public.profiles on delete set null,action text not null,entity_type text not null,entity_id text,details jsonb not null default '{}'::jsonb,created_at timestamptz not null default now());
create index idx_admin_audit_created on public.admin_audit_log(created_at desc);

insert into public.subscription_plans(code,name,description,duration_months,is_active) values ('free','Free','Permanent free membership',0,true),('one-month','One month','One month access',1,false),('two-month','Two months','Two months access',2,false),('three-month','Three months','Three months access',3,false),('annual','Annual','Twelve months access',12,false) on conflict(code) do nothing;
insert into public.feature_catalog(feature_key,name,category,description) values ('marine-conditions','Marine conditions','Tools','Weather, tides and sea conditions'),('fishing-tools','Fishing tools','Tools','Fishing activity tools and recommendations'),('community','Community','Community','Fishing, surfing and kayaking channels'),('image-uploads','Image uploads','Community','Upload photographs to conversations'),('premium-insights','Premium insights','Premium','Future advanced analysis and forecasts') on conflict(feature_key) do nothing;
insert into public.plan_features(plan_code,feature_key) select 'free',feature_key from public.feature_catalog where feature_key<>'premium-insights' on conflict do nothing;

alter table public.subscription_plans enable row level security;alter table public.member_subscriptions enable row level security;alter table public.feature_catalog enable row level security;alter table public.plan_features enable row level security;alter table public.admin_audit_log enable row level security;
grant select on public.subscription_plans,public.feature_catalog,public.plan_features,public.member_subscriptions to authenticated;grant select,insert,update,delete on public.subscription_plans,public.member_subscriptions,public.feature_catalog,public.plan_features to authenticated;grant select,insert on public.admin_audit_log to authenticated;
create policy "view plans" on public.subscription_plans for select to authenticated using(is_active or public.is_admin());create policy "admin plans" on public.subscription_plans for all to authenticated using(public.is_admin()) with check(public.is_admin());
create policy "view own subscriptions" on public.member_subscriptions for select to authenticated using(user_id=auth.uid() or public.is_admin());create policy "admin subscriptions" on public.member_subscriptions for all to authenticated using(public.is_admin()) with check(public.is_admin());
create policy "view features" on public.feature_catalog for select to authenticated using(is_active or public.is_admin());create policy "admin features" on public.feature_catalog for all to authenticated using(public.is_admin()) with check(public.is_admin());
create policy "view plan features" on public.plan_features for select to authenticated using(true);create policy "admin plan features" on public.plan_features for all to authenticated using(public.is_admin()) with check(public.is_admin());
create policy "admin audit" on public.admin_audit_log for select to authenticated using(public.is_admin());create policy "admin writes audit" on public.admin_audit_log for insert to authenticated with check(public.is_admin() and admin_id=auth.uid());
create policy "admin updates profiles" on public.profiles for update to authenticated using(public.is_admin()) with check(public.is_admin());create policy "admin updates contacts" on public.audience_contacts for update to authenticated using(public.is_admin()) with check(public.is_admin());create policy "admin deletes attachments" on public.community_attachments for delete to authenticated using(public.is_admin());
