import {NextRequest,NextResponse} from "next/server";
import {createClient} from "@supabase/supabase-js";
import {createSupabaseAdmin} from "@/lib/supabase/admin";

async function context(req:NextRequest){const admin=createSupabaseAdmin(),token=req.headers.get("authorization")?.replace(/^Bearer\s+/i,"");const url=process.env.NEXT_PUBLIC_SUPABASE_URL,key=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY;if(!admin||!token||!url||!key)return null;const auth=createClient(url,key,{global:{headers:{Authorization:`Bearer ${token}`}},auth:{persistSession:false}});const{data:{user}}=await auth.auth.getUser(token);if(!user)return null;const{data:p}=await admin.from("profiles").select("role").eq("id",user.id).single();return p?.role==="admin"?{admin,user}:null}

export async function GET(req:NextRequest){const ctx=await context(req);if(!ctx)return NextResponse.json({error:"Administrator access required."},{status:403});const{admin}=ctx;const[members,plans,subscriptions,messages,media,features,planFeatures,audit,learningCourses,learningSections,learningLessons,learningResources,courseAccess,authUsers]=await Promise.all([
admin.from("audience_contacts").select("user_id,email,plan,subscription_status,marketing_consent,lifecycle_stage,last_seen_at,created_at,profiles(display_name,role,account_status,country,city)").order("created_at",{ascending:false}),
admin.from("subscription_plans").select("*").order("duration_months"),
admin.from("member_subscriptions").select("*,subscription_plans(name),profiles(display_name)").order("created_at",{ascending:false}).limit(500),
admin.from("community_messages").select("id,channel,content,author_id,parent_id,created_at,profiles!community_messages_author_id_fkey(display_name),community_attachments(id)").order("created_at",{ascending:false}).limit(200),
admin.from("community_attachments").select("id,message_id,owner_id,storage_path,public_url,file_name,mime_type,size_bytes,created_at,profiles!community_attachments_owner_id_fkey(display_name)").order("created_at",{ascending:false}).limit(200),
admin.from("feature_catalog").select("*").order("category").order("name"),admin.from("plan_features").select("*"),admin.from("admin_audit_log").select("id,action,entity_type,entity_id,details,created_at,profiles(display_name)").order("created_at",{ascending:false}).limit(100),
admin.from("learning_courses").select("*").order("sort_order"),admin.from("learning_sections").select("*").order("sort_order"),admin.from("learning_lessons").select("*").order("sort_order"),admin.from("learning_resources").select("*").order("sort_order"),admin.from("course_plan_access").select("*"),admin.auth.admin.listUsers({page:1,perPage:1000})]);
const err=[members,plans,subscriptions,messages,media,features,planFeatures,audit,learningCourses,learningSections,learningLessons,learningResources,courseAccess].find(x=>x.error)?.error;if(err)return NextResponse.json({error:err.message},{status:400});const authMap=Object.fromEntries((authUsers.data?.users??[]).map(u=>[u.id,{confirmed_at:u.email_confirmed_at,last_sign_in_at:u.last_sign_in_at}]));return NextResponse.json({members:(members.data??[]).map(m=>({...m,auth:authMap[m.user_id]})),plans:plans.data,subscriptions:subscriptions.data,messages:messages.data,media:media.data,features:features.data,planFeatures:planFeatures.data,audit:audit.data,learningCourses:learningCourses.data,learningSections:learningSections.data,learningLessons:learningLessons.data,learningResources:learningResources.data,courseAccess:courseAccess.data})}

export async function POST(req:NextRequest){const ctx=await context(req);if(!ctx)return NextResponse.json({error:"Administrator access required."},{status:403});const{admin,user}=ctx,body=await req.json(),action=String(body.action??"");let result:{error?:{message:string}|null,data?:unknown}={};let entity="system",entityId="";
if(action==="invite_user"){entity="user";const r=await admin.auth.admin.inviteUserByEmail(String(body.email),{data:{display_name:String(body.display_name||body.email)}});result={data:r.data,error:r.error};entityId=r.data.user?.id??""}
else if(action==="delete_user"){entity="user";entityId=String(body.user_id);if(entityId===user.id)return NextResponse.json({error:"You cannot delete your own administrator account."},{status:400});result=await admin.auth.admin.deleteUser(entityId)}
else if(action==="set_role"){entity="profile";entityId=String(body.user_id);result=await admin.from("profiles").update({role:body.role}).eq("id",entityId)}
else if(action==="set_account_status"){entity="profile";entityId=String(body.user_id);result=await admin.from("profiles").update({account_status:body.status,banned:body.status==="suspended"}).eq("id",entityId)}
else if(action==="update_contact"){entity="contact";entityId=String(body.user_id);result=await admin.from("audience_contacts").update({lifecycle_stage:body.lifecycle_stage,marketing_consent:body.marketing_consent,marketing_consent_at:body.marketing_consent?new Date().toISOString():null,updated_at:new Date().toISOString()}).eq("user_id",entityId)}
else if(action==="save_plan"){entity="plan";entityId=String(body.code).toLowerCase().replace(/[^a-z0-9-]/g,"-");result=await admin.from("subscription_plans").upsert({code:entityId,name:body.name,description:body.description??"",duration_months:Number(body.duration_months),price_amount:Number(body.price_amount),currency:String(body.currency||"USD").toUpperCase(),is_active:Boolean(body.is_active),updated_at:new Date().toISOString()})}
else if(action==="delete_plan"){entity="plan";entityId=String(body.code);if(entityId==="free")return NextResponse.json({error:"The free plan cannot be deleted."},{status:400});result=await admin.from("subscription_plans").delete().eq("code",entityId)}
else if(action==="assign_subscription"){entity="subscription";const{data:plan,error}=await admin.from("subscription_plans").select("code,duration_months").eq("code",body.plan_code).single();if(error)return NextResponse.json({error:error.message},{status:400});const starts=new Date(body.starts_at||Date.now()),ends=plan.duration_months?new Date(starts):null;if(ends)ends.setMonth(ends.getMonth()+plan.duration_months);await admin.from("member_subscriptions").update({status:"cancelled",updated_at:new Date().toISOString()}).eq("user_id",body.user_id).in("status",["active","trialing"]);const r=await admin.from("member_subscriptions").insert({user_id:body.user_id,plan_code:plan.code,status:"active",duration_months:plan.duration_months,starts_at:starts.toISOString(),ends_at:ends?.toISOString()??null,auto_renew:Boolean(body.auto_renew),notes:body.notes??""}).select("id").single();result=r;entityId=r.data?.id??"";if(!r.error)await admin.from("audience_contacts").update({plan:plan.code,subscription_status:"active",updated_at:new Date().toISOString()}).eq("user_id",body.user_id)}
else if(action==="cancel_subscription"){entity="subscription";entityId=String(body.id);result=await admin.from("member_subscriptions").update({status:"cancelled",auto_renew:false,updated_at:new Date().toISOString()}).eq("id",entityId)}
else if(action==="save_feature"){entity="feature";entityId=String(body.feature_key).toLowerCase().replace(/[^a-z0-9-]/g,"-");result=await admin.from("feature_catalog").upsert({feature_key:entityId,name:body.name,category:body.category??"general",description:body.description??"",is_active:Boolean(body.is_active)})}
else if(action==="toggle_plan_feature"){entity="plan_feature";entityId=`${body.plan_code}:${body.feature_key}`;result=body.enabled?await admin.from("plan_features").upsert({plan_code:body.plan_code,feature_key:body.feature_key,enabled:true}):await admin.from("plan_features").delete().eq("plan_code",body.plan_code).eq("feature_key",body.feature_key)}
else if(action==="save_learning_course"){entity="learning_course";const values={slug:String(body.slug).toLowerCase().replace(/[^a-z0-9-]/g,"-"),title_en:String(body.title_en),title_ar:String(body.title_ar||""),description_en:String(body.description_en||""),description_ar:String(body.description_ar||""),level:String(body.level||"Beginner"),thumbnail_url:body.thumbnail_url||null,status:String(body.status||"draft"),sort_order:Number(body.sort_order||0),updated_at:new Date().toISOString()};const r=body.id?await admin.from("learning_courses").update(values).eq("id",body.id).select("id").single():await admin.from("learning_courses").insert(values).select("id").single();result=r;entityId=r.data?.id??String(body.id||"")}
else if(action==="delete_learning_course"){entity="learning_course";entityId=String(body.id);const{data:sectionRows}=await admin.from("learning_sections").select("id").eq("course_id",entityId),sectionIds=(sectionRows??[]).map(x=>x.id);if(sectionIds.length){const{data:lessonRows}=await admin.from("learning_lessons").select("id").in("section_id",sectionIds),lessonIds=(lessonRows??[]).map(x=>x.id);if(lessonIds.length){const{data:files}=await admin.from("learning_resources").select("storage_path").in("lesson_id",lessonIds).not("storage_path","is",null);if(files?.length)await admin.storage.from("course-resources").remove(files.map(x=>x.storage_path))}}result=await admin.from("learning_courses").delete().eq("id",entityId)}
else if(action==="save_learning_section"){entity="learning_section";const values={course_id:String(body.course_id),title_en:String(body.title_en),title_ar:String(body.title_ar||""),sort_order:Number(body.sort_order||0),updated_at:new Date().toISOString()};const r=body.id?await admin.from("learning_sections").update(values).eq("id",body.id).select("id").single():await admin.from("learning_sections").insert(values).select("id").single();result=r;entityId=r.data?.id??String(body.id||"")}
else if(action==="delete_learning_section"){entity="learning_section";entityId=String(body.id);const{data:lessonRows}=await admin.from("learning_lessons").select("id").eq("section_id",entityId),lessonIds=(lessonRows??[]).map(x=>x.id);if(lessonIds.length){const{data:files}=await admin.from("learning_resources").select("storage_path").in("lesson_id",lessonIds).not("storage_path","is",null);if(files?.length)await admin.storage.from("course-resources").remove(files.map(x=>x.storage_path))}result=await admin.from("learning_sections").delete().eq("id",entityId)}
else if(action==="save_learning_lesson"){entity="learning_lesson";const values={section_id:String(body.section_id),title_en:String(body.title_en),title_ar:String(body.title_ar||""),description_en:String(body.description_en||""),description_ar:String(body.description_ar||""),lesson_type:String(body.lesson_type||"video"),duration_minutes:Number(body.duration_minutes||0),video_provider:String(body.video_provider||"external"),video_id:body.video_id||null,video_url:body.video_url||null,article_body:String(body.article_body||""),is_preview:Boolean(body.is_preview),status:String(body.status||"draft"),sort_order:Number(body.sort_order||0),updated_at:new Date().toISOString()};const r=body.id?await admin.from("learning_lessons").update(values).eq("id",body.id).select("id").single():await admin.from("learning_lessons").insert(values).select("id").single();result=r;entityId=r.data?.id??String(body.id||"")}
else if(action==="delete_learning_lesson"){entity="learning_lesson";entityId=String(body.id);const{data:files}=await admin.from("learning_resources").select("storage_path").eq("lesson_id",entityId).not("storage_path","is",null);if(files?.length)await admin.storage.from("course-resources").remove(files.map(x=>x.storage_path));result=await admin.from("learning_lessons").delete().eq("id",entityId)}
else if(action==="save_learning_resource"){entity="learning_resource";const r=await admin.from("learning_resources").insert({lesson_id:String(body.lesson_id),title:String(body.title),resource_type:String(body.resource_type),storage_path:body.storage_path||null,external_url:body.external_url||null,file_name:body.file_name||null,mime_type:body.mime_type||null,size_bytes:body.size_bytes?Number(body.size_bytes):null,sort_order:Number(body.sort_order||0)}).select("id").single();result=r;entityId=r.data?.id??""}
else if(action==="delete_learning_resource"){entity="learning_resource";entityId=String(body.id);if(body.storage_path)await admin.storage.from("course-resources").remove([String(body.storage_path)]);result=await admin.from("learning_resources").delete().eq("id",entityId)}
else if(action==="toggle_course_plan"){entity="course_plan_access";entityId=`${body.course_id}:${body.plan_code}`;result=body.enabled?await admin.from("course_plan_access").upsert({course_id:body.course_id,plan_code:body.plan_code}):await admin.from("course_plan_access").delete().eq("course_id",body.course_id).eq("plan_code",body.plan_code)}
else if(action==="delete_message"){entity="message";entityId=String(body.id);const{data:files}=await admin.from("community_attachments").select("storage_path").eq("message_id",entityId);if(files?.length)await admin.storage.from("community-media").remove(files.map(x=>x.storage_path));result=await admin.from("community_messages").delete().eq("id",entityId)}
else if(action==="bulk_delete_messages"){entity="message";const ids=Array.isArray(body.ids)?body.ids.map(String).slice(0,100):[];if(!ids.length)return NextResponse.json({error:"Select at least one message."},{status:400});entityId=`${ids.length} messages`;const{data:replies}=await admin.from("community_messages").select("id").in("parent_id",ids),messageIds=[...ids,...(replies??[]).map(x=>x.id)];const{data:files}=await admin.from("community_attachments").select("storage_path").in("message_id",messageIds);if(files?.length)await admin.storage.from("community-media").remove(files.map(x=>x.storage_path));result=await admin.from("community_messages").delete().in("id",ids)}
else if(action==="delete_media"){entity="media";entityId=String(body.id);await admin.storage.from("community-media").remove([String(body.storage_path)]);result=await admin.from("community_attachments").delete().eq("id",entityId)}
else return NextResponse.json({error:"Unknown administrator action."},{status:400});
if(result.error)return NextResponse.json({error:result.error.message},{status:400});await admin.from("admin_audit_log").insert({admin_id:user.id,action,entity_type:entity,entity_id:entityId,details:{summary:body.summary??action}});return NextResponse.json({ok:true,data:result.data})}
